INSERT INTO dma_counties (state, state_abbr, county, state_fips, dma_name, msa) VALUES
('KENTUCKY','KY','BRACKEN','21','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','BREATHITT','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','BRECKINRIDGE','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','BULLITT','21','Louisville, KY - IN DMA','Louisville, KY - IN MSA'),
('KENTUCKY','KY','BUTLER','21','Bowling Green, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CALDWELL','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CALLOWAY','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CAMPBELL','21','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('KENTUCKY','KY','CARLISLE','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CARROLL','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CARTER','21','Charleston - Huntington, WV - KY - OH DMA','Huntington - Ashland, WV - KY - OH MSA'),
('KENTUCKY','KY','CASEY','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CHRISTIAN','21','Nashville, TN - KY DMA','Clarksville - Hopkinsville, TN - KY MSA'),
('KENTUCKY','KY','CLARK','21','Lexington, KY DMA','Lexington, KY MSA'),
('KENTUCKY','KY','CLAY','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CLINTON','21','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CRITTENDEN','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','CUMBERLAND','21','Bowling Green, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','DAVIESS','21','Evansville, IN - IL - KY DMA','Owensboro, KY MSA'),
('KENTUCKY','KY','EDMONSON','21','Bowling Green, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','ELLIOTT','21','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','ESTILL','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','FAYETTE','21','Lexington, KY DMA','Lexington, KY MSA'),
('KENTUCKY','KY','FLEMING','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','FLOYD','21','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','FRANKLIN','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','FULTON','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','GALLATIN','21','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('KENTUCKY','KY','GARRARD','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','GRANT','21','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('KENTUCKY','KY','GRAVES','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','GRAYSON','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','GREEN','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','GREENUP','21','Charleston - Huntington, WV - KY - OH DMA','Huntington - Ashland, WV - KY - OH MSA'),
('KENTUCKY','KY','HANCOCK','21','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','HARDIN','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','HARLAN','21','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','HARRISON','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','HART','21','Bowling Green, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','HENDERSON','21','Evansville, IN - IL - KY DMA','Evansville - Henderson, IN - KY MSA'),
('KENTUCKY','KY','HENRY','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','HICKMAN','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','HOPKINS','21','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','JACKSON','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','JEFFERSON','21','Louisville, KY - IN DMA','Louisville, KY - IN MSA'),
('KENTUCKY','KY','JESSAMINE','21','Lexington, KY DMA','Lexington, KY MSA'),
('KENTUCKY','KY','JOHNSON','21','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','KENTON','21','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('KENTUCKY','KY','KNOTT','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','KNOX','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LARUE','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LAUREL','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LAWRENCE','21','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LEE','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LESLIE','21','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LETCHER','21','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LEWIS','21','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LINCOLN','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LIVINGSTON','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LOGAN','21','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','LYON','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MCCRACKEN','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MCCREARY','21','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MCLEAN','21','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MADISON','21','Lexington, KY DMA','Lexington, KY MSA'),
('KENTUCKY','KY','MAGOFFIN','21','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MARION','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MARSHALL','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MARTIN','21','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MASON','21','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MEADE','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MENIFEE','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MERCER','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','METCALFE','21','Bowling Green, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MONROE','21','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MONTGOMERY','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MORGAN','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','MUHLENBERG','21','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','NELSON','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','NICHOLAS','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','OHIO','21','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','OLDHAM','21','Louisville, KY - IN DMA','Louisville, KY - IN MSA'),
('KENTUCKY','KY','OWEN','21','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','OWSLEY','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','PENDLETON','21','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('KENTUCKY','KY','PERRY','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','PIKE','21','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','POWELL','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','PULASKI','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','ROBERTSON','21','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','ROCKCASTLE','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','ROWAN','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','RUSSELL','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','SCOTT','21','Lexington, KY DMA','Lexington, KY MSA'),
('KENTUCKY','KY','SHELBY','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','SIMPSON','21','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','SPENCER','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','TAYLOR','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','TODD','21','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','TRIGG','21','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','TRIMBLE','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','UNION','21','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','WARREN','21','Bowling Green, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','WASHINGTON','21','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','WAYNE','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','WEBSTER','21','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','WHITLEY','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','WOLFE','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','WOODFORD','21','Lexington, KY DMA','Lexington, KY MSA'),
('LOUISIANA','LA','ACADIA','22','Lafayette, LA DMA','Lafayette, LA MSA'),
('LOUISIANA','LA','ALLEN','22','Lake Charles, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','ASCENSION','22','Baton Rouge, LA - MS DMA','Baton Rouge, LA MSA'),
('LOUISIANA','LA','ASSUMPTION','22','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','AVOYELLES','22','Alexandria, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','BEAUREGARD','22','Lake Charles, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','BIENVILLE','22','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','BOSSIER','22','Shreveport, LA - AR - OK - TX DMA','Shreveport - Bossier City, LA MSA'),
('LOUISIANA','LA','CADDO','22','Shreveport, LA - AR - OK - TX DMA','Shreveport - Bossier City, LA MSA'),
('LOUISIANA','LA','CALCASIEU','22','Lake Charles, LA DMA','Lake Charles, LA MSA'),
('LOUISIANA','LA','CALDWELL','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','CAMERON','22','Lake Charles, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','CATAHOULA','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','CLAIBORNE','22','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','CONCORDIA','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','DE SOTO','22','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','EAST BATON ROUGE','22','Baton Rouge, LA - MS DMA','Baton Rouge, LA MSA'),
('LOUISIANA','LA','EAST CARROLL','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','EAST FELICIANA','22','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','EVANGELINE','22','Lafayette, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','FRANKLIN','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','GRANT','22','Alexandria, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','IBERIA','22','Lafayette, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','IBERVILLE','22','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','JACKSON','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','JEFFERSON','22','New Orleans, LA - MS DMA','New Orleans, LA MSA'),
('LOUISIANA','LA','JEFFERSON DAVIS','22','Lafayette, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','LAFAYETTE','22','Lafayette, LA DMA','Lafayette, LA MSA'),
('LOUISIANA','LA','LAFOURCHE','22','New Orleans, LA - MS DMA','Houma, LA MSA'),
('LOUISIANA','LA','LA SALLE','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','LINCOLN','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','LIVINGSTON','22','Baton Rouge, LA - MS DMA','Baton Rouge, LA MSA'),
('LOUISIANA','LA','MADISON','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','MOREHOUSE','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','NATCHITOCHES','22','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','ORLEANS','22','New Orleans, LA - MS DMA','New Orleans, LA MSA'),
('LOUISIANA','LA','OUACHITA','22','Monroe - El Dorado, LA - AR DMA','Monroe, LA MSA'),
('LOUISIANA','LA','PLAQUEMINES','22','New Orleans, LA - MS DMA','New Orleans, LA MSA'),
('LOUISIANA','LA','POINTE COUPEE','22','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','RAPIDES','22','Alexandria, LA DMA','Alexandria, LA MSA'),
('LOUISIANA','LA','RED RIVER','22','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','RICHLAND','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','SABINE','22','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','ST BERNARD','22','New Orleans, LA - MS DMA','New Orleans, LA MSA'),
('LOUISIANA','LA','ST CHARLES','22','New Orleans, LA - MS DMA','New Orleans, LA MSA'),
('LOUISIANA','LA','ST HELENA','22','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','ST JAMES','22','New Orleans, LA - MS DMA','New Orleans, LA MSA'),
('LOUISIANA','LA','ST JOHN THE BAP','22','New Orleans, LA - MS DMA','New Orleans, LA MSA'),
('LOUISIANA','LA','ST LANDRY','22','Lafayette, LA DMA','Lafayette, LA MSA'),
('LOUISIANA','LA','ST MARTIN','22','Lafayette, LA DMA','Lafayette, LA MSA'),
('LOUISIANA','LA','ST MARY','22','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','ST TAMMANY','22','New Orleans, LA - MS DMA','New Orleans, LA MSA'),
('LOUISIANA','LA','TANGIPAHOA','22','New Orleans, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','TENSAS','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','TERREBONNE','22','New Orleans, LA - MS DMA','Houma, LA MSA'),
('LOUISIANA','LA','UNION','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','VERMILION','22','Lafayette, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','VERNON','22','Alexandria, LA DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','WASHINGTON','22','New Orleans, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','WEBSTER','22','Shreveport, LA - AR - OK - TX DMA','Shreveport - Bossier City, LA MSA'),
('LOUISIANA','LA','WEST BATON ROUGE','22','Baton Rouge, LA - MS DMA','Baton Rouge, LA MSA'),
('LOUISIANA','LA','WEST CARROLL','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','WEST FELICIANA','22','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('LOUISIANA','LA','WINN','22','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','ANDROSCOGGIN','23','Portland - Auburn, ME - NH - VT DMA','Lewiston - Auburn, ME NECMA'),
('MAINE','ME','AROOSTOOK','23','Presque Isle, ME DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','CUMBERLAND','23','Portland - Auburn, ME - NH - VT DMA','Portland, ME NECMA'),
('MAINE','ME','FRANKLIN','23','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','HANCOCK','23','Bangor, ME DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','KENNEBEC','23','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','KNOX','23','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','LINCOLN','23','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','OXFORD','23','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','PENOBSCOT','23','Bangor, ME DMA','Bangor, ME NECMA'),
('MAINE','ME','PISCATAQUIS','23','Bangor, ME DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','SAGADAHOC','23','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','SOMERSET','23','Bangor, ME DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','WALDO','23','Bangor, ME DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','WASHINGTON','23','Bangor, ME DMA','Not Assigned to Metro Area (NAM)'),
('MAINE','ME','YORK','23','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','ALLEGANY','24','Washington, DC - MD - PA - VA - WV DMA','Cumberland, MD - WV MSA'),
('MARYLAND','MD','ANNE ARUNDEL','24','Baltimore, MD DMA','Baltimore, MD PMSA'),
('MARYLAND','MD','BALTIMORE','24','Baltimore, MD DMA','Baltimore, MD PMSA'),
('MARYLAND','MD','CALVERT','24','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('MARYLAND','MD','CAROLINE','24','Baltimore, MD DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','CARROLL','24','Baltimore, MD DMA','Baltimore, MD PMSA'),
('MARYLAND','MD','CECIL','24','Baltimore, MD DMA','Wilmington - Newark, DE - MD PMSA'),
('MARYLAND','MD','CHARLES','24','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('MARYLAND','MD','DORCHESTER','24','Baltimore, MD DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','FREDERICK','24','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('MARYLAND','MD','GARRETT','24','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','HARFORD','24','Baltimore, MD DMA','Baltimore, MD PMSA'),
('MARYLAND','MD','HOWARD','24','Baltimore, MD DMA','Baltimore, MD PMSA'),
('MARYLAND','MD','KENT','24','Baltimore, MD DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','MONTGOMERY','24','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('MARYLAND','MD','PRINCE GEORGES','24','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('MARYLAND','MD','QUEEN ANNES','24','Baltimore, MD DMA','Baltimore, MD PMSA'),
('MARYLAND','MD','ST MARYS','24','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','SOMERSET','24','Salisbury, MD - DE DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','TALBOT','24','Baltimore, MD DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','WASHINGTON','24','Washington, DC - MD - PA - VA - WV DMA','Hagerstown, MD PMSA'),
('MARYLAND','MD','WICOMICO','24','Salisbury, MD - DE DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','WORCESTER','24','Salisbury, MD - DE DMA','Not Assigned to Metro Area (NAM)'),
('MARYLAND','MD','BALTIMORE CITY','24','Baltimore, MD DMA','Baltimore, MD PMSA'),
('MASSACHUSETTS','MA','BARNSTABLE','25','Boston, MA - NH DMA','Barnstable - Yarmouth, MA NECMA'),
('MASSACHUSETTS','MA','BERKSHIRE','25','Albany - Schenectady - Troy, NY - MA - VT DMA','Pittsfield, MA NECMA'),
('MASSACHUSETTS','MA','BRISTOL','25','Providence, RI - New Bedford, MA DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('MASSACHUSETTS','MA','DUKES','25','Boston, MA - NH DMA','Not Assigned to Metro Area (NAM)'),
('MASSACHUSETTS','MA','ESSEX','25','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('MASSACHUSETTS','MA','FRANKLIN','25','Springfield - Holyoke, MA DMA','Not Assigned to Metro Area (NAM)'),
('MASSACHUSETTS','MA','HAMPDEN','25','Springfield - Holyoke, MA DMA','Springfield, MA NECMA'),
('MASSACHUSETTS','MA','HAMPSHIRE','25','Springfield - Holyoke, MA DMA','Springfield, MA NECMA'),
('MASSACHUSETTS','MA','MIDDLESEX','25','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('MASSACHUSETTS','MA','NANTUCKET','25','Boston, MA - NH DMA','Not Assigned to Metro Area (NAM)'),
('MASSACHUSETTS','MA','NORFOLK','25','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('MASSACHUSETTS','MA','PLYMOUTH','25','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('MASSACHUSETTS','MA','SUFFOLK','25','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('MASSACHUSETTS','MA','WORCESTER','25','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('MICHIGAN','MI','ALCONA','26','Alpena, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','ALGER','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','ALLEGAN','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Grand Rapids - Muskegon - Holland, MI MSA'),
('MICHIGAN','MI','ALPENA','26','Alpena, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','ANTRIM','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','ARENAC','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','BARAGA','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','BARRY','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','BAY','26','Flint - Saginaw - Bay City, MI DMA','Saginaw - Bay City - Midland, MI MSA'),
('MICHIGAN','MI','BENZIE','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','BERRIEN','26','South Bend - Elkhart, IN - MI DMA','Benton Harbor, MI MSA'),
('MICHIGAN','MI','BRANCH','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','CALHOUN','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Kalamazoo - Battle Creek, MI MSA'),
('MICHIGAN','MI','CASS','26','South Bend - Elkhart, IN - MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','CHARLEVOIX','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','CHEBOYGAN','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','CHIPPEWA','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','CLARE','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','CLINTON','26','Lansing, MI DMA','Lansing - East Lansing, MI MSA'),
('MICHIGAN','MI','CRAWFORD','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','DELTA','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','DICKINSON','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','EATON','26','Lansing, MI DMA','Lansing - East Lansing, MI MSA'),
('MICHIGAN','MI','EMMET','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','GENESEE','26','Flint - Saginaw - Bay City, MI DMA','Flint, MI PMSA'),
('MICHIGAN','MI','GLADWIN','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','GOGEBIC','26','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','GRAND TRAVERSE','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','GRATIOT','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','HILLSDALE','26','Lansing, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','HOUGHTON','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','HURON','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','INGHAM','26','Lansing, MI DMA','Lansing - East Lansing, MI MSA'),
('MICHIGAN','MI','IONIA','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','IOSCO','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','IRON','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','ISABELLA','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','JACKSON','26','Lansing, MI DMA','Jackson, MI MSA'),
('MICHIGAN','MI','KALAMAZOO','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Kalamazoo - Battle Creek, MI MSA'),
('MICHIGAN','MI','KALKASKA','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','KENT','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Grand Rapids - Muskegon - Holland, MI MSA'),
('MICHIGAN','MI','KEWEENAW','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','LAKE','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','LAPEER','26','Detroit, MI DMA','Detroit, MI PMSA'),
('MICHIGAN','MI','LEELANAU','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','LENAWEE','26','Toledo, OH - MI DMA','Ann Arbor, MI PMSA'),
('MICHIGAN','MI','LIVINGSTON','26','Detroit, MI DMA','Ann Arbor, MI PMSA'),
('MICHIGAN','MI','LUCE','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MACKINAC','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MACOMB','26','Detroit, MI DMA','Detroit, MI PMSA'),
('MICHIGAN','MI','MANISTEE','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MARQUETTE','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MASON','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MECOSTA','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MENOMINEE','26','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MIDLAND','26','Flint - Saginaw - Bay City, MI DMA','Saginaw - Bay City - Midland, MI MSA'),
('MICHIGAN','MI','MISSAUKEE','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MONROE','26','Detroit, MI DMA','Detroit, MI PMSA'),
('MICHIGAN','MI','MONTCALM','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MONTMORENCY','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','MUSKEGON','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Grand Rapids - Muskegon - Holland, MI MSA'),
('MICHIGAN','MI','NEWAYGO','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','OAKLAND','26','Detroit, MI DMA','Detroit, MI PMSA'),
('MICHIGAN','MI','OCEANA','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','OGEMAW','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','ONTONAGON','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','OSCEOLA','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','OSCODA','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','OTSEGO','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','OTTAWA','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Grand Rapids - Muskegon - Holland, MI MSA'),
('MICHIGAN','MI','PRESQUE ISLE','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','ROSCOMMON','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','SAGINAW','26','Flint - Saginaw - Bay City, MI DMA','Saginaw - Bay City - Midland, MI MSA'),
('MICHIGAN','MI','ST CLAIR','26','Detroit, MI DMA','Detroit, MI PMSA'),
('MICHIGAN','MI','ST JOSEPH','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','SANILAC','26','Detroit, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','SCHOOLCRAFT','26','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','SHIAWASSEE','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','TUSCOLA','26','Flint - Saginaw - Bay City, MI DMA','Not Assigned to Metro Area (NAM)'),
('MICHIGAN','MI','VAN BUREN','26','Grand Rapids - Kalamazoo - Battle Creek, MI DMA','Kalamazoo - Battle Creek, MI MSA'),
('MICHIGAN','MI','WASHTENAW','26','Detroit, MI DMA','Ann Arbor, MI PMSA'),
('MICHIGAN','MI','WAYNE','26','Detroit, MI DMA','Detroit, MI PMSA'),
('MICHIGAN','MI','WEXFORD','26','Traverse City - Cadillac, MI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','AITKIN','27','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','ANOKA','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','BECKER','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','BELTRAMI','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','BENTON','27','Minneapolis - St. Paul, MN - WI DMA','St. Cloud, MN MSA'),
('MINNESOTA','MN','BIG STONE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','BLUE EARTH','27','Mankato, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','BROWN','27','Mankato, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','CARLTON','27','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','CARVER','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','CASS','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','CHIPPEWA','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','CHISAGO','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','CLAY','27','Fargo - Valley City, ND - MN DMA','Fargo - Moorhead, ND - MN MSA'),
('MINNESOTA','MN','CLEARWATER','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','COOK','27','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','COTTONWOOD','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','CROW WING','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','DAKOTA','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','DODGE','27','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','DOUGLAS','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','FARIBAULT','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','FILLMORE','27','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','FREEBORN','27','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','GOODHUE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','GRANT','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','HENNEPIN','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','HOUSTON','27','LaCrosse - Eau Claire, WI - MN DMA','LaCrosse, WI - MN MSA'),
('MINNESOTA','MN','HUBBARD','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','ISANTI','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','ITASCA','27','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','JACKSON','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','KANABEC','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','KANDIYOHI','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','KITTSON','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','KOOCHICHING','27','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','LAC QUI PARLE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','LAKE','27','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','LAKE OF WOODS','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','LE SUEUR','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','LINCOLN','27','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','LYON','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MCLEOD','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MAHNOMEN','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MARSHALL','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MARTIN','27','Mankato, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MEEKER','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MILLE LACS','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MORRISON','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MOWER','27','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','MURRAY','27','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','NICOLLET','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','NOBLES','27','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','NORMAN','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','OLMSTED','27','Rochester - Mason City - Austin, MN - IA DMA','Rochester, MN MSA'),
('MINNESOTA','MN','OTTER TAIL','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','PENNINGTON','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','PINE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','PIPESTONE','27','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','POLK','27','Fargo - Valley City, ND - MN DMA','Grand Forks, ND - MN MSA'),
('MINNESOTA','MN','POPE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','RAMSEY','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','RED LAKE','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','REDWOOD','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','RENVILLE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','RICE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','ROCK','27','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','ROSEAU','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','ST LOUIS','27','Duluth - Superior, MN - MI - WI DMA','Duluth - Superior, MN - WI MSA'),
('MINNESOTA','MN','SCOTT','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','SHERBURNE','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','SIBLEY','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','STEARNS','27','Minneapolis - St. Paul, MN - WI DMA','St. Cloud, MN MSA'),
('MINNESOTA','MN','STEELE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','STEVENS','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','SWIFT','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','TODD','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','TRAVERSE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','WABASHA','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','WADENA','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','WASECA','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','WASHINGTON','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','WATONWAN','27','Mankato, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','WILKIN','27','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','WINONA','27','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('MINNESOTA','MN','WRIGHT','27','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('MINNESOTA','MN','YELLOW MEDICINE','27','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','ADAMS','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','ALCORN','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','AMITE','28','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','ATTALA','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','BENTON','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','BOLIVAR','28','Greenwood - Greenville, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','CALHOUN','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','CARROLL','28','Greenwood - Greenville, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','CHICKASAW','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','CHOCTAW','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','CLAIBORNE','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','CLARKE','28','Meridian, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','CLAY','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','COAHOMA','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','COPIAH','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','COVINGTON','28','Hattiesburg - Laurel, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','DE SOTO','28','Memphis, TN - AR- MS - MO DMA','Memphis, TN - AR - MS MSA'),
('MISSISSIPPI','MS','FORREST','28','Hattiesburg - Laurel, MS DMA','Hattiesburg, MS MSA'),
('MISSISSIPPI','MS','FRANKLIN','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','GEORGE','28','Biloxi - Gulfport, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','GREENE','28','Mobile, AL - Pensacola, FL - MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','GRENADA','28','Greenwood - Greenville, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','HANCOCK','28','New Orleans, LA - MS DMA','Biloxi - Gulfport - Pascagoula, MS MSA'),
('MISSISSIPPI','MS','HARRISON','28','Biloxi - Gulfport, MS DMA','Biloxi - Gulfport - Pascagoula, MS MSA'),
('MISSISSIPPI','MS','HINDS','28','Jackson, MS DMA','Jackson, MS MSA'),
('MISSISSIPPI','MS','HOLMES','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','HUMPHREYS','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','ISSAQUENA','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','ITAWAMBA','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','JACKSON','28','Biloxi - Gulfport, MS DMA','Biloxi - Gulfport - Pascagoula, MS MSA'),
('MISSISSIPPI','MS','JASPER','28','Hattiesburg - Laurel, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','JEFFERSON','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','JEFFERSON DAVIS','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','JONES','28','Hattiesburg - Laurel, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','KEMPER','28','Meridian, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','LAFAYETTE','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','LAMAR','28','Hattiesburg - Laurel, MS DMA','Hattiesburg, MS MSA'),
('MISSISSIPPI','MS','LAUDERDALE','28','Meridian, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','LAWRENCE','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','LEAKE','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','LEE','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','LEFLORE','28','Greenwood - Greenville, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','LINCOLN','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','LOWNDES','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','MADISON','28','Jackson, MS DMA','Jackson, MS MSA'),
('MISSISSIPPI','MS','MARION','28','Hattiesburg - Laurel, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','MARSHALL','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','MONROE','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','MONTGOMERY','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','NESHOBA','28','Meridian, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','NEWTON','28','Meridian, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','NOXUBEE','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','OKTIBBEHA','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','PANOLA','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','PEARL RIVER','28','New Orleans, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','PERRY','28','Hattiesburg - Laurel, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','PIKE','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','PONTOTOC','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','PRENTISS','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','QUITMAN','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','RANKIN','28','Jackson, MS DMA','Jackson, MS MSA'),
('MISSISSIPPI','MS','SCOTT','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','SHARKEY','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','SIMPSON','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','SMITH','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','STONE','28','Biloxi - Gulfport, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','SUNFLOWER','28','Greenwood - Greenville, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','TALLAHATCHIE','28','Greenwood - Greenville, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','TATE','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','TIPPAH','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','TISHOMINGO','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','TUNICA','28','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','UNION','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','WALTHALL','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','WARREN','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','WASHINGTON','28','Greenwood - Greenville, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','WAYNE','28','Hattiesburg - Laurel, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','WEBSTER','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','WILKINSON','28','Baton Rouge, LA - MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','WINSTON','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','YALOBUSHA','28','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('MISSISSIPPI','MS','YAZOO','28','Jackson, MS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','ADAIR','29','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','ANDREW','29','St. Joseph, MO - KS DMA','St. Joseph, MO MSA'),
('MISSOURI','MO','ATCHISON','29','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','AUDRAIN','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','BARRY','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','BARTON','29','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','BATES','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','BENTON','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','BOLLINGER','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','BOONE','29','Columbia - Jefferson City, MO DMA','Columbia, MO MSA'),
('MISSOURI','MO','BUCHANAN','29','St. Joseph, MO - KS DMA','St. Joseph, MO MSA'),
('MISSOURI','MO','BUTLER','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CALDWELL','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CALLAWAY','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CAMDEN','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CAPE GIRARDEAU','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CARROLL','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CARTER','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CASS','29','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('MISSOURI','MO','CEDAR','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CHARITON','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)');
