INSERT INTO dma_counties (state, state_abbr, county, state_fips, dma_name, msa) VALUES
('WEST VIRGINIA','WV','BERKELEY','54','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('WEST VIRGINIA','WV','BOONE','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','BRAXTON','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','BROOKE','54','Wheeling - Steubenville, WV - OH DMA','Steubenville - Weirton, OH - WV MSA'),
('WEST VIRGINIA','WV','CABELL','54','Charleston - Huntington, WV - KY - OH DMA','Huntington - Ashland, WV - KY - OH MSA'),
('WEST VIRGINIA','WV','CALHOUN','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','CLAY','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','DODDRIDGE','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','FAYETTE','54','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','GILMER','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','GRANT','54','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','GREENBRIER','54','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','HAMPSHIRE','54','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','HANCOCK','54','Wheeling - Steubenville, WV - OH DMA','Steubenville - Weirton, OH - WV MSA'),
('WEST VIRGINIA','WV','HARDY','54','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','HARRISON','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','JACKSON','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','JEFFERSON','54','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('WEST VIRGINIA','WV','KANAWHA','54','Charleston - Huntington, WV - KY - OH DMA','Charleston, WV MSA'),
('WEST VIRGINIA','WV','LEWIS','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','LINCOLN','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','LOGAN','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','MCDOWELL','54','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','MARION','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','MARSHALL','54','Wheeling - Steubenville, WV - OH DMA','Wheeling, WV - OH MSA'),
('WEST VIRGINIA','WV','MASON','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','MERCER','54','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','MINERAL','54','Washington, DC - MD - PA - VA - WV DMA','Cumberland, MD - WV MSA'),
('WEST VIRGINIA','WV','MINGO','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','MONONGALIA','54','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','MONROE','54','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','MORGAN','54','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','NICHOLAS','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','OHIO','54','Wheeling - Steubenville, WV - OH DMA','Wheeling, WV - OH MSA'),
('WEST VIRGINIA','WV','PENDLETON','54','Harrisonburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','PLEASANTS','54','Parkersburg, WV - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','POCAHONTAS','54','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','PRESTON','54','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','PUTNAM','54','Charleston - Huntington, WV - KY - OH DMA','Charleston, WV MSA'),
('WEST VIRGINIA','WV','RALEIGH','54','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','RANDOLPH','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','RITCHIE','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','ROANE','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','SUMMERS','54','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','TAYLOR','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','TUCKER','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','TYLER','54','Wheeling - Steubenville, WV - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','UPSHUR','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','WAYNE','54','Charleston - Huntington, WV - KY - OH DMA','Huntington - Ashland, WV - KY - OH MSA'),
('WEST VIRGINIA','WV','WEBSTER','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','WETZEL','54','Wheeling - Steubenville, WV - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','WIRT','54','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('WEST VIRGINIA','WV','WOOD','54','Parkersburg, WV - OH DMA','Parkersburg - Marietta, WV - OH MSA'),
('WEST VIRGINIA','WV','WYOMING','54','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','ADAMS','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','ASHLAND','55','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','BARRON','55','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','BAYFIELD','55','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','BROWN','55','Green Bay - Appleton, WI - MI DMA','Green Bay, WI MSA'),
('WISCONSIN','WI','BUFFALO','55','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','BURNETT','55','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','CALUMET','55','Green Bay - Appleton, WI - MI DMA','Appleton - Oshkosh - Neenah, WI MSA'),
('WISCONSIN','WI','CHIPPEWA','55','LaCrosse - Eau Claire, WI - MN DMA','Eau Claire, WI MSA'),
('WISCONSIN','WI','CLARK','55','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','COLUMBIA','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','CRAWFORD','55','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','DANE','55','Madison, WI DMA','Madison, WI MSA'),
('WISCONSIN','WI','DODGE','55','Milwaukee, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','DOOR','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','DOUGLAS','55','Duluth - Superior, MN - MI - WI DMA','Duluth - Superior, MN - WI MSA'),
('WISCONSIN','WI','DUNN','55','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','EAU CLAIRE','55','LaCrosse - Eau Claire, WI - MN DMA','Eau Claire, WI MSA'),
('WISCONSIN','WI','FLORENCE','55','Marquette, MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','FOND DU LAC','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','FOREST','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','GRANT','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','GREEN','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','GREEN LAKE','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','IOWA','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','IRON','55','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','JACKSON','55','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','JEFFERSON','55','Milwaukee, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','JUNEAU','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','KENOSHA','55','Milwaukee, WI DMA','Kenosha, WI PMSA'),
('WISCONSIN','WI','KEWAUNEE','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','LA CROSSE','55','LaCrosse - Eau Claire, WI - MN DMA','LaCrosse, WI - MN MSA'),
('WISCONSIN','WI','LAFAYETTE','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','LANGLADE','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','LINCOLN','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','MANITOWOC','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','MARATHON','55','Wausau - Rhinelander, WI DMA','Wausau, WI MSA'),
('WISCONSIN','WI','MARINETTE','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','MARQUETTE','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','MENOMINEE','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','MILWAUKEE','55','Milwaukee, WI DMA','Milwaukee - Waukesha, WI PMSA'),
('WISCONSIN','WI','MONROE','55','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','OCONTO','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','ONEIDA','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','OUTAGAMIE','55','Green Bay - Appleton, WI - MI DMA','Appleton - Oshkosh - Neenah, WI MSA'),
('WISCONSIN','WI','OZAUKEE','55','Milwaukee, WI DMA','Milwaukee - Waukesha, WI PMSA'),
('WISCONSIN','WI','PEPIN','55','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','PIERCE','55','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('WISCONSIN','WI','POLK','55','Minneapolis - St. Paul, MN - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','PORTAGE','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','PRICE','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','RACINE','55','Milwaukee, WI DMA','Racine, WI PMSA'),
('WISCONSIN','WI','RICHLAND','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','ROCK','55','Madison, WI DMA','Janesville - Beloit, WI MSA'),
('WISCONSIN','WI','RUSK','55','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','ST CROIX','55','Minneapolis - St. Paul, MN - WI DMA','Minneapolis - St. Paul, MN - WI MSA'),
('WISCONSIN','WI','SAUK','55','Madison, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','SAWYER','55','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','SHAWANO','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','SHEBOYGAN','55','Milwaukee, WI DMA','Sheboygan, WI MSA'),
('WISCONSIN','WI','TAYLOR','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','TREMPEALEAU','55','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','VERNON','55','LaCrosse - Eau Claire, WI - MN DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','VILAS','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','WALWORTH','55','Milwaukee, WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','WASHBURN','55','Duluth - Superior, MN - MI - WI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','WASHINGTON','55','Milwaukee, WI DMA','Milwaukee - Waukesha, WI PMSA'),
('WISCONSIN','WI','WAUKESHA','55','Milwaukee, WI DMA','Milwaukee - Waukesha, WI PMSA'),
('WISCONSIN','WI','WAUPACA','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','WAUSHARA','55','Green Bay - Appleton, WI - MI DMA','Not Assigned to Metro Area (NAM)'),
('WISCONSIN','WI','WINNEBAGO','55','Green Bay - Appleton, WI - MI DMA','Appleton - Oshkosh - Neenah, WI MSA'),
('WISCONSIN','WI','WOOD','55','Wausau - Rhinelander, WI DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','ALBANY','56','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','BIG HORN','56','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','CAMPBELL','56','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','CARBON','56','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','CONVERSE','56','Casper - Riverton, WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','CROOK','56','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','FREMONT','56','Casper - Riverton, WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','GOSHEN','56','Cheyenne - Scottsbluff - Sterling, WY - NE DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','HOT SPRINGS','56','Casper - Riverton, WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','JOHNSON','56','Casper - Riverton, WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','LARAMIE','56','Cheyenne - Scottsbluff - Sterling, WY - NE DMA','Cheyenne, WY MSA'),
('WYOMING','WY','LINCOLN','56','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','NATRONA','56','Casper - Riverton, WY DMA','Casper, WY MSA'),
('WYOMING','WY','NIOBRARA','56','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','PARK','56','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','PLATTE','56','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','SHERIDAN','56','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','SUBLETTE','56','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','SWEETWATER','56','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','TETON','56','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','UINTA','56','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','WASHAKIE','56','Casper - Riverton, WY DMA','Not Assigned to Metro Area (NAM)'),
('WYOMING','WY','WESTON','56','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)');
