INSERT INTO dma_counties (state, state_abbr, county, state_fips, dma_name, msa) VALUES
('ALABAMA','AL','AUTAUGA','01','Montgomery, AL DMA','Montgomery, AL MSA'),
('ALABAMA','AL','BALDWIN','01','Mobile, AL - Pensacola, FL - MS DMA','Mobile, AL MSA'),
('ALABAMA','AL','BARBOUR','01','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','BIBB','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','BLOUNT','01','Birmingham, AL DMA','Birmingham, AL MSA'),
('ALABAMA','AL','BULLOCK','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','BUTLER','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CALHOUN','01','Birmingham, AL DMA','Anniston, AL MSA'),
('ALABAMA','AL','CHAMBERS','01','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CHEROKEE','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CHILTON','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CHOCTAW','01','Meridian, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CLARKE','01','Mobile, AL - Pensacola, FL - MS DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CLAY','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CLEBURNE','01','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','COFFEE','01','Dothan, AL - GA DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','COLBERT','01','Huntsville - Decatur - Florence, AL - TN DMA','Florence, AL MSA'),
('ALABAMA','AL','CONECUH','01','Mobile, AL - Pensacola, FL - MS DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','COOSA','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','COVINGTON','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CRENSHAW','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','CULLMAN','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','DALE','01','Dothan, AL - GA DMA','Dothan, AL MSA'),
('ALABAMA','AL','DALLAS','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','DE KALB','01','Huntsville - Decatur - Florence, AL - TN DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','ELMORE','01','Montgomery, AL DMA','Montgomery, AL MSA'),
('ALABAMA','AL','ESCAMBIA','01','Mobile, AL - Pensacola, FL - MS DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','ETOWAH','01','Birmingham, AL DMA','Gadsden, AL MSA'),
('ALABAMA','AL','FAYETTE','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','FRANKLIN','01','Huntsville - Decatur - Florence, AL - TN DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','GENEVA','01','Dothan, AL - GA DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','GREENE','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','HALE','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','HENRY','01','Dothan, AL - GA DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','HOUSTON','01','Dothan, AL - GA DMA','Dothan, AL MSA'),
('ALABAMA','AL','JACKSON','01','Huntsville - Decatur - Florence, AL - TN DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','JEFFERSON','01','Birmingham, AL DMA','Birmingham, AL MSA'),
('ALABAMA','AL','LAMAR','01','Columbus - Tupelo - West Point, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','LAUDERDALE','01','Huntsville - Decatur - Florence, AL - TN DMA','Florence, AL MSA'),
('ALABAMA','AL','LAWRENCE','01','Huntsville - Decatur - Florence, AL - TN DMA','Decatur, AL MSA'),
('ALABAMA','AL','LEE','01','Columbus, GA - AL DMA','Columbus, GA - AL MSA'),
('ALABAMA','AL','LIMESTONE','01','Huntsville - Decatur - Florence, AL - TN DMA','Huntsville, AL MSA'),
('ALABAMA','AL','LOWNDES','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','MACON','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','MADISON','01','Huntsville - Decatur - Florence, AL - TN DMA','Huntsville, AL MSA'),
('ALABAMA','AL','MARENGO','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','MARION','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','MARSHALL','01','Huntsville - Decatur - Florence, AL - TN DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','MOBILE','01','Mobile, AL - Pensacola, FL - MS DMA','Mobile, AL MSA'),
('ALABAMA','AL','MONROE','01','Mobile, AL - Pensacola, FL - MS DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','MONTGOMERY','01','Montgomery, AL DMA','Montgomery, AL MSA'),
('ALABAMA','AL','MORGAN','01','Huntsville - Decatur - Florence, AL - TN DMA','Decatur, AL MSA'),
('ALABAMA','AL','PERRY','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','PICKENS','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','PIKE','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','RANDOLPH','01','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','RUSSELL','01','Columbus, GA - AL DMA','Columbus, GA - AL MSA'),
('ALABAMA','AL','ST CLAIR','01','Birmingham, AL DMA','Birmingham, AL MSA'),
('ALABAMA','AL','SHELBY','01','Birmingham, AL DMA','Birmingham, AL MSA'),
('ALABAMA','AL','SUMTER','01','Meridian, MS - AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','TALLADEGA','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','TALLAPOOSA','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','TUSCALOOSA','01','Birmingham, AL DMA','Tuscaloosa, AL MSA'),
('ALABAMA','AL','WALKER','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','WASHINGTON','01','Mobile, AL - Pensacola, FL - MS DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','WILCOX','01','Montgomery, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALABAMA','AL','WINSTON','01','Birmingham, AL DMA','Not Assigned to Metro Area (NAM)'),
('ALASKA','AK','ALEUTIANS EAST BOR. 1','02','Unmeasured, AK DMA',''),
('ALASKA','AK','ALEUTIANS WEST C.A. 2','02','Unmeasured, AK DMA',''),
('ALASKA','AK','ANCHORAGE BOR. 3','02','Anchorage, AK DMA',''),
('ALASKA','AK','BETHEL C.A. 4','02','Unmeasured, AK DMA',''),
('ALASKA','AK','BRISTOL BAY BOR. 5','02','Unmeasured, AK DMA',''),
('ALASKA','AK','DENALI BOR. 6','02','Fairbanks, AK DMA',''),
('ALASKA','AK','DILLINGHAM C.A. 7','02','Unmeasured, AK DMA',''),
('ALASKA','AK','FAIRBANKS NO.STAR BOR8.','02','Fairbanks, AK DMA',''),
('ALASKA','AK','HAINES BOR. 9','02','Unmeasured, AK DMA',''),
('ALASKA','AK','JUNEAU BOR. 10','02','Juneau, AK DMA',''),
('ALASKA','AK','KENAI PENINSULA BOR. 11','02','Anchorage, AK DMA',''),
('ALASKA','AK','KETCHIKAN GATEWAY B1O2','02','Unmeasured, AK DMA',''),
('ALASKA','AK','KODIAK ISLAND BOR. 13','02','Unmeasured, AK DMA',''),
('ALASKA','AK','LAKE & PENINSULA BOR14','02','Unmeasured, AK DMA',''),
('ALASKA','AK','MATANUSKA-SUSITNA B1O5','02','Anchorage, AK DMA',''),
('ALASKA','AK','NOME C.A. 16','02','Unmeasured, AK DMA',''),
('ALASKA','AK','NORTH SLOPE BOR. 17','02','Unmeasured, AK DMA',''),
('ALASKA','AK','NORTHWEST ARCTIC BO1R8.','02','Unmeasured, AK DMA',''),
('ALASKA','AK','PR.WALES-OUT.KET.C.A 19','02','Unmeasured, AK DMA',''),
('ALASKA','AK','SITKA BOR. 20','02','Unmeasured, AK DMA',''),
('ALASKA','AK','SKAGWAY-HOO.-ANG.C.A21','02','Unmeasured, AK DMA',''),
('ALASKA','AK','SOUTHEAST FRBKS. C.A 22','02','Fairbanks, AK DMA',''),
('ALASKA','AK','VALDEZ-CORDOVA C.A. 23','02','Unmeasured, AK DMA',''),
('ALASKA','AK','WADE HAMPTON C.A. 24','02','Unmeasured, AK DMA',''),
('ALASKA','AK','WRANGELL-PETERS. C.A25','02','Unmeasured, AK DMA',''),
('ALASKA','AK','YAKUTAT BOR. 26','02','Unmeasured, AK DMA',''),
('ALASKA','AK','YUKON-KOYUKUK C.A. 27','02','Unmeasured, AK DMA',''),
('ARIZONA','AZ','APACHE','04','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','COCHISE','04','Tucson (Nogales), AZ DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','COCONINO','04','Phoenix, AZ DMA','Flagstaff, AZ - UT MSA'),
('ARIZONA','AZ','GILA','04','Phoenix, AZ DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','GRAHAM','04','Phoenix, AZ DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','GREENLEE','04','Phoenix, AZ DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','LA PAZ','04','Phoenix, AZ DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','MARICOPA','04','Phoenix, AZ DMA','Phoenix - Mesa, AZ MSA'),
('ARIZONA','AZ','MOHAVE','04','Phoenix, AZ DMA','Las Vegas, NV - AZ MSA'),
('ARIZONA','AZ','NAVAJO','04','Phoenix, AZ DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','PIMA','04','Tucson (Nogales), AZ DMA','Tucson, AZ MSA'),
('ARIZONA','AZ','PINAL','04','Phoenix, AZ DMA','Phoenix - Mesa, AZ MSA'),
('ARIZONA','AZ','SANTA CRUZ','04','Tucson (Nogales), AZ DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','YAVAPAI','04','Phoenix, AZ DMA','Not Assigned to Metro Area (NAM)'),
('ARIZONA','AZ','YUMA','04','Yuma - El Centro, AZ - CA DMA','Yuma, AZ MSA'),
('ARKANSAS','AR','ARKANSAS','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','ASHLEY','05','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','BAXTER','05','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','BENTON','05','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Fayetteville - Springdale - Rogers, AR MSA'),
('ARKANSAS','AR','BOONE','05','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','BRADLEY','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CALHOUN','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CARROLL','05','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CHICOT','05','Greenwood - Greenville, MS DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CLARK','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CLAY','05','Jonesboro, AR - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CLEBURNE','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CLEVELAND','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','COLUMBIA','05','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CONWAY','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','CRAIGHEAD','05','Jonesboro, AR - MO DMA','Jonesboro, AR MSA'),
('ARKANSAS','AR','CRAWFORD','05','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Fort Smith, AR - OK MSA'),
('ARKANSAS','AR','CRITTENDEN','05','Memphis, TN - AR- MS - MO DMA','Memphis, TN - AR - MS MSA'),
('ARKANSAS','AR','CROSS','05','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','DALLAS','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','DESHA','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','DREW','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','FAULKNER','05','Little Rock - Pine Bluff, AR DMA','Little Rock - North Little Rock, AR MSA'),
('ARKANSAS','AR','FRANKLIN','05','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','FULTON','05','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','GARLAND','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','GRANT','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','GREENE','05','Jonesboro, AR - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','HEMPSTEAD','05','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','HOT SPRING','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','HOWARD','05','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','INDEPENDENCE','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','IZARD','05','Jonesboro, AR - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','JACKSON','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','JEFFERSON','05','Little Rock - Pine Bluff, AR DMA','Pine Bluff, AR MSA'),
('ARKANSAS','AR','JOHNSON','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','LAFAYETTE','05','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','LAWRENCE','05','Jonesboro, AR - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','LEE','05','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','LINCOLN','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','LITTLE RIVER','05','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','LOGAN','05','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','LONOKE','05','Little Rock - Pine Bluff, AR DMA','Little Rock - North Little Rock, AR MSA'),
('ARKANSAS','AR','MADISON','05','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','MARION','05','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','MILLER','05','Shreveport, LA - AR - OK - TX DMA','Texarkana, TX - Texarkana, AR MSA'),
('ARKANSAS','AR','MISSISSIPPI','05','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','MONROE','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','MONTGOMERY','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','NEVADA','05','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','NEWTON','05','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','OUACHITA','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','PERRY','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','PHILLIPS','05','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','PIKE','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','POINSETT','05','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','POLK','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','POPE','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','PRAIRIE','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','PULASKI','05','Little Rock - Pine Bluff, AR DMA','Little Rock - North Little Rock, AR MSA'),
('ARKANSAS','AR','RANDOLPH','05','Jonesboro, AR - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','ST FRANCIS','05','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','SALINE','05','Little Rock - Pine Bluff, AR DMA','Little Rock - North Little Rock, AR MSA'),
('ARKANSAS','AR','SCOTT','05','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','SEARCY','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','SEBASTIAN','05','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Fort Smith, AR - OK MSA'),
('ARKANSAS','AR','SEVIER','05','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','SHARP','05','Jonesboro, AR - MO DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','STONE','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','UNION','05','Monroe - El Dorado, LA - AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','VAN BUREN','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','WASHINGTON','05','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Fayetteville - Springdale - Rogers, AR MSA'),
('ARKANSAS','AR','WHITE','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','WOODRUFF','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('ARKANSAS','AR','YELL','05','Little Rock - Pine Bluff, AR DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','ALAMEDA','06','San Francisco - Oakland - San Jose, CA DMA','Oakland, CA PMSA'),
('CALIFORNIA','CA','ALPINE','06','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','AMADOR','06','Sacramento - Stockton - Modesto, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','BUTTE','06','Chico - Redding, CA DMA','Chico - Paradise, CA MSA'),
('CALIFORNIA','CA','CALAVERAS','06','Sacramento - Stockton - Modesto, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','COLUSA','06','Sacramento - Stockton - Modesto, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','CONTRA COSTA','06','San Francisco - Oakland - San Jose, CA DMA','Oakland, CA PMSA'),
('CALIFORNIA','CA','DEL NORTE','06','Eureka, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','EL DORADO','06','Sacramento - Stockton - Modesto, CA DMA','Sacramento, CA PMSA'),
('CALIFORNIA','CA','FRESNO','06','Fresno - Visalia, CA DMA','Fresno, CA MSA'),
('CALIFORNIA','CA','GLENN','06','Chico - Redding, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','HUMBOLDT','06','Eureka, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','IMPERIAL','06','Yuma - El Centro, AZ - CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','INYO','06','Los Angeles, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','KERN','06','Bakersfield, CA DMA','Bakersfield, CA MSA'),
('CALIFORNIA','CA','KINGS','06','Fresno - Visalia, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','LAKE','06','San Francisco - Oakland - San Jose, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','LASSEN','06','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','LOS ANGELES','06','Los Angeles, CA DMA','Los Angeles - Long Beach, CA PMSA'),
('CALIFORNIA','CA','MADERA','06','Fresno - Visalia, CA DMA','Fresno, CA MSA'),
('CALIFORNIA','CA','MARIN','06','San Francisco - Oakland - San Jose, CA DMA','San Francisco, CA PMSA'),
('CALIFORNIA','CA','MARIPOSA','06','Fresno - Visalia, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','MENDOCINO','06','San Francisco - Oakland - San Jose, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','MERCED','06','Fresno - Visalia, CA DMA','Merced, CA MSA'),
('CALIFORNIA','CA','MODOC','06','Medford - Klamath Falls, OR - CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','MONO','06','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','MONTEREY','06','Monterey - Salinas, CA DMA','Salinas, CA MSA'),
('CALIFORNIA','CA','NAPA','06','San Francisco - Oakland - San Jose, CA DMA','Vallejo - Fairfield - Napa, CA PMSA'),
('CALIFORNIA','CA','NEVADA','06','Sacramento - Stockton - Modesto, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','ORANGE','06','Los Angeles, CA DMA','Orange County, CA PMSA'),
('CALIFORNIA','CA','PLACER','06','Sacramento - Stockton - Modesto, CA DMA','Sacramento, CA PMSA'),
('CALIFORNIA','CA','PLUMAS','06','Sacramento - Stockton - Modesto, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','RIVERSIDE','06','Palm Springs, CA DMA','Riverside - San Bernardino, CA PMSA'),
('CALIFORNIA','CA','SACRAMENTO','06','Sacramento - Stockton - Modesto, CA DMA','Sacramento, CA PMSA'),
('CALIFORNIA','CA','SAN BENITO','06','Monterey - Salinas, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','SAN BERNARDINO','06','Los Angeles, CA DMA','Riverside - San Bernardino, CA PMSA'),
('CALIFORNIA','CA','SAN DIEGO','06','San Diego, CA DMA','San Diego, CA MSA'),
('CALIFORNIA','CA','SAN FRANCISCO','06','San Francisco - Oakland - San Jose, CA DMA','San Francisco, CA PMSA'),
('CALIFORNIA','CA','SAN JOAQUIN','06','Sacramento - Stockton - Modesto, CA DMA','Stockton - Lodi, CA MSA'),
('CALIFORNIA','CA','SAN LUIS OBISPO','06','Santa Barbara - Santa Maria - San Luis Obispo, CA DMA','San Luis Obispo - Atascadero - Paso Robles, CA MSA'),
('CALIFORNIA','CA','SAN MATEO','06','San Francisco - Oakland - San Jose, CA DMA','San Francisco, CA PMSA'),
('CALIFORNIA','CA','SANTA BARBARA','06','Santa Barbara - Santa Maria - San Luis Obispo, CA DMA','Santa Barbara - Santa Maria - Lompoc, CA MSA'),
('CALIFORNIA','CA','SANTA CLARA','06','San Francisco - Oakland - San Jose, CA DMA','San Jose, CA PMSA'),
('CALIFORNIA','CA','SANTA CRUZ','06','Monterey - Salinas, CA DMA','Santa Cruz - Watsonville, CA PMSA'),
('CALIFORNIA','CA','SHASTA','06','Chico - Redding, CA DMA','Redding, CA MSA'),
('CALIFORNIA','CA','SIERRA','06','Sacramento - Stockton - Modesto, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','SISKIYOU','06','Medford - Klamath Falls, OR - CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','SOLANO','06','San Francisco - Oakland - San Jose, CA DMA','Vallejo - Fairfield - Napa, CA PMSA'),
('CALIFORNIA','CA','SONOMA','06','San Francisco - Oakland - San Jose, CA DMA','Santa Rosa, CA PMSA'),
('CALIFORNIA','CA','STANISLAUS','06','Sacramento - Stockton - Modesto, CA DMA','Modesto, CA MSA'),
('CALIFORNIA','CA','SUTTER','06','Sacramento - Stockton - Modesto, CA DMA','Yuba City, CA MSA'),
('CALIFORNIA','CA','TEHAMA','06','Chico - Redding, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','TRINITY','06','Chico - Redding, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','TULARE','06','Fresno - Visalia, CA DMA','Visalia - Tulare - Porterville, CA MSA'),
('CALIFORNIA','CA','TUOLUMNE','06','Sacramento - Stockton - Modesto, CA DMA','Not Assigned to Metro Area (NAM)'),
('CALIFORNIA','CA','VENTURA','06','Los Angeles, CA DMA','Ventura, CA PMSA'),
('CALIFORNIA','CA','YOLO','06','Sacramento - Stockton - Modesto, CA DMA','Yolo, CA PMSA'),
('CALIFORNIA','CA','YUBA','06','Sacramento - Stockton - Modesto, CA DMA','Yuba City, CA MSA'),
('COLORADO','CO','ADAMS','08','Denver, CO - NE - NV - WY DMA','Denver, CO PMSA'),
('COLORADO','CO','ALAMOSA','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','ARAPAHOE','08','Denver, CO - NE - NV - WY DMA','Denver, CO PMSA'),
('COLORADO','CO','ARCHULETA','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','BACA','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','BENT','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','BOULDER','08','Denver, CO - NE - NV - WY DMA','Boulder - Longmont, CO PMSA'),
('COLORADO','CO','CHAFFEE','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','CHEYENNE','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','CLEAR CREEK','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','CONEJOS','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','COSTILLA','08','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','CROWLEY','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','CUSTER','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','DELTA','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','DENVER','08','Denver, CO - NE - NV - WY DMA','Denver, CO PMSA'),
('COLORADO','CO','DOLORES','08','Grand Junction - Montrose, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','DOUGLAS','08','Denver, CO - NE - NV - WY DMA','Denver, CO PMSA'),
('COLORADO','CO','EAGLE','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','ELBERT','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','EL PASO','08','Colorado Springs - Pueblo, CO DMA','Colorado Springs, CO MSA'),
('COLORADO','CO','FREMONT','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','GARFIELD','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','GILPIN','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','GRAND','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','GUNNISON','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','HINSDALE','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','HUERFANO','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','JACKSON','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','JEFFERSON','08','Denver, CO - NE - NV - WY DMA','Denver, CO PMSA'),
('COLORADO','CO','KIOWA','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','KIT CARSON','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','LAKE','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','LA PLATA','08','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','LARIMER','08','Denver, CO - NE - NV - WY DMA','Fort Collins - Loveland, CO MSA'),
('COLORADO','CO','LAS ANIMAS','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','LINCOLN','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','LOGAN','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','MESA','08','Grand Junction - Montrose, CO DMA','Grand Junction, CO MSA'),
('COLORADO','CO','MINERAL','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','MOFFAT','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','MONTEZUMA','08','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','MONTROSE','08','Grand Junction - Montrose, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','MORGAN','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','OTERO','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','OURAY','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','PARK','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','PHILLIPS','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','PITKIN','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','PROWERS','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','PUEBLO','08','Colorado Springs - Pueblo, CO DMA','Pueblo, CO MSA'),
('COLORADO','CO','RIO BLANCO','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','RIO GRANDE','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','ROUTT','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','SAGUACHE','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','SAN JUAN','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','SAN MIGUEL','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','SEDGWICK','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','SUMMIT','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','TELLER','08','Colorado Springs - Pueblo, CO DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','WASHINGTON','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('COLORADO','CO','WELD','08','Denver, CO - NE - NV - WY DMA','Greeley, CO PMSA'),
('COLORADO','CO','YUMA','08','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('CONNECTICUT','CT','HARTFORD','09','Hartford & New Haven, CT DMA','Hartford, CT NECMA'),
('CONNECTICUT','CT','TOLLAND','09','Hartford & New Haven, CT DMA','Hartford, CT NECMA'),
('CONNECTICUT','CT','WINDHAM','09','Hartford & New Haven, CT DMA','Not Assigned to Metro Area (NAM)'),
('CONNECTICUT','CT','LITCHFIELD','09','Hartford & New Haven, CT DMA','Not Assigned to Metro Area (NAM)'),
('CONNECTICUT','CT','MIDDLESEX','09','Hartford & New Haven, CT DMA','Hartford, CT NECMA'),
('CONNECTICUT','CT','NEW LONDON','09','Hartford & New Haven, CT DMA','New London - Norwich, CT NECMA'),
('CONNECTICUT','CT','FAIRFIELD','09','New York, NY - CT - NJ - PA DMA','New Haven- Bridgeport- Stamford- Waterbury- Danbury,CT NECMA'),
('CONNECTICUT','CT','NEW HAVEN','09','Hartford & New Haven, CT DMA','New Haven- Bridgeport- Stamford- Waterbury- Danbury,CT NECMA'),
('DELAWARE','DE','KENT','10','Philadelphia, PA - DE - NJ DMA','Dover, DE MSA'),
('DELAWARE','DE','NEW CASTLE','10','Philadelphia, PA - DE - NJ DMA','Wilmington - Newark, DE - MD PMSA'),
('DELAWARE','DE','SUSSEX','10','Salisbury, MD - DE DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','ALACHUA','12','Gainesville, FL DMA','Gainesville, FL MSA'),
('FLORIDA','FL','BAKER','12','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','BAY','12','Panama City, FL DMA','Panama City, FL MSA'),
('FLORIDA','FL','BRADFORD','12','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','BREVARD','12','Orlando - Daytona Beach - Melbourne, FL DMA','Melbourne - Titusville - Palm Bay, FL MSA'),
('FLORIDA','FL','BROWARD','12','Miami - Ft. Lauderdale, FL DMA','Fort Lauderdale, FL PMSA'),
('FLORIDA','FL','CALHOUN','12','Panama City, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','CHARLOTTE','12','Ft. Myers - Naples, FL DMA','Punta Gorda, FL MSA'),
('FLORIDA','FL','CITRUS','12','Tampa - St. Petersburg - Sarasota, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','CLAY','12','Jacksonville, FL - Brunswick, GA DMA','Jacksonville, FL MSA'),
('FLORIDA','FL','COLLIER','12','Ft. Myers - Naples, FL DMA','Naples, FL MSA'),
('FLORIDA','FL','COLUMBIA','12','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','DADE','12','Miami - Ft. Lauderdale, FL DMA','Miami, FL PMSA'),
('FLORIDA','FL','DE SOTO','12','Ft. Myers - Naples, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','DIXIE','12','Gainesville, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','DUVAL','12','Jacksonville, FL - Brunswick, GA DMA','Jacksonville, FL MSA'),
('FLORIDA','FL','ESCAMBIA','12','Mobile, AL - Pensacola, FL - MS DMA','Pensacola, FL MSA'),
('FLORIDA','FL','FLAGLER','12','Orlando - Daytona Beach - Melbourne, FL DMA','Daytona Beach, FL MSA'),
('FLORIDA','FL','FRANKLIN','12','Panama City, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','GADSDEN','12','Tallahassee - Thomasville, FL - GA DMA','Tallahassee, FL MSA'),
('FLORIDA','FL','GILCHRIST','12','Gainesville, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','GLADES','12','Ft. Myers - Naples, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','GULF','12','Panama City, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','HAMILTON','12','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','HARDEE','12','Tampa - St. Petersburg - Sarasota, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','HENDRY','12','Ft. Myers - Naples, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','HERNANDO','12','Tampa - St. Petersburg - Sarasota, FL DMA','Tampa - St. Petersburg - Clearwater, FL MSA'),
('FLORIDA','FL','HIGHLANDS','12','Tampa - St. Petersburg - Sarasota, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','HILLSBOROUGH','12','Tampa - St. Petersburg - Sarasota, FL DMA','Tampa - St. Petersburg - Clearwater, FL MSA'),
('FLORIDA','FL','HOLMES','12','Panama City, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','INDIAN RIVER','12','West Palm Beach - Ft. Pierce, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','JACKSON','12','Panama City, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','JEFFERSON','12','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','LAFAYETTE','12','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','LAKE','12','Orlando - Daytona Beach - Melbourne, FL DMA','Orlando, FL MSA'),
('FLORIDA','FL','LEE','12','Ft. Myers - Naples, FL DMA','Fort Myers - Cape Coral, FL MSA'),
('FLORIDA','FL','LEON','12','Tallahassee - Thomasville, FL - GA DMA','Tallahassee, FL MSA'),
('FLORIDA','FL','LEVY','12','Gainesville, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','LIBERTY','12','Panama City, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','MADISON','12','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','MANATEE','12','Tampa - St. Petersburg - Sarasota, FL DMA','Sarasota - Bradenton, FL MSA'),
('FLORIDA','FL','MARION','12','Orlando - Daytona Beach - Melbourne, FL DMA','Ocala, FL MSA'),
('FLORIDA','FL','MARTIN','12','West Palm Beach - Ft. Pierce, FL DMA','Fort Pierce - Port St. Lucie, FL MSA'),
('FLORIDA','FL','MIAMI-DADE','12','Miami - Ft. Lauderdale, FL DMA','Miami, FL PMSA'),
('FLORIDA','FL','MONROE','12','Miami - Ft. Lauderdale, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','NASSAU','12','Jacksonville, FL - Brunswick, GA DMA','Jacksonville, FL MSA'),
('FLORIDA','FL','OKALOOSA','12','Mobile, AL - Pensacola, FL - MS DMA','Fort Walton Beach, FL MSA'),
('FLORIDA','FL','OKEECHOBEE','12','West Palm Beach - Ft. Pierce, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','ORANGE','12','Orlando - Daytona Beach - Melbourne, FL DMA','Orlando, FL MSA'),
('FLORIDA','FL','OSCEOLA','12','Orlando - Daytona Beach - Melbourne, FL DMA','Orlando, FL MSA'),
('FLORIDA','FL','PALM BEACH','12','West Palm Beach - Ft. Pierce, FL DMA','West Palm Beach - Boca Raton, FL MSA'),
('FLORIDA','FL','PASCO','12','Tampa - St. Petersburg - Sarasota, FL DMA','Tampa - St. Petersburg - Clearwater, FL MSA'),
('FLORIDA','FL','PINELLAS','12','Tampa - St. Petersburg - Sarasota, FL DMA','Tampa - St. Petersburg - Clearwater, FL MSA'),
('FLORIDA','FL','POLK','12','Tampa - St. Petersburg - Sarasota, FL DMA','Lakeland - Winter Haven, FL MSA'),
('FLORIDA','FL','PUTNAM','12','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','ST. JOHNS','12','Jacksonville, FL - Brunswick, GA DMA','Jacksonville, FL MSA'),
('FLORIDA','FL','ST. LUCIE','12','West Palm Beach - Ft. Pierce, FL DMA','Fort Pierce - Port St. Lucie, FL MSA'),
('FLORIDA','FL','SANTA ROSA','12','Mobile, AL - Pensacola, FL - MS DMA','Pensacola, FL MSA'),
('FLORIDA','FL','SARASOTA','12','Tampa - St. Petersburg - Sarasota, FL DMA','Sarasota - Bradenton, FL MSA'),
('FLORIDA','FL','SEMINOLE','12','Orlando - Daytona Beach - Melbourne, FL DMA','Orlando, FL MSA'),
('FLORIDA','FL','SUMTER','12','Orlando - Daytona Beach - Melbourne, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','SUWANNEE','12','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','TAYLOR','12','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','UNION','12','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','VOLUSIA','12','Orlando - Daytona Beach - Melbourne, FL DMA','Daytona Beach, FL MSA'),
('FLORIDA','FL','WAKULLA','12','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','WALTON','12','Panama City, FL DMA','Not Assigned to Metro Area (NAM)'),
('FLORIDA','FL','WASHINGTON','12','Panama City, FL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','APPLING','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','ATKINSON','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BACON','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BAKER','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BALDWIN','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BANKS','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BARROW','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','BARTOW','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','BEN HILL','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BERRIEN','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BIBB','13','Macon, GA DMA','Macon, GA MSA'),
('GEORGIA','GA','BLECKLEY','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BRANTLEY','13','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BROOKS','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BRYAN','13','Savannah, GA - SC DMA','Savannah, GA MSA'),
('GEORGIA','GA','BULLOCH','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BURKE','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','BUTTS','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','CALHOUN','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','CAMDEN','13','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','CANDLER','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','CARROLL','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','CATOOSA','13','Chattanooga, TN - GA - NC DMA','Chattanooga, TN - GA MSA'),
('GEORGIA','GA','CHARLTON','13','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','CHATHAM','13','Savannah, GA - SC DMA','Savannah, GA MSA'),
('GEORGIA','GA','CHATTAHOOCHEE','13','Columbus, GA - AL DMA','Columbus, GA - AL MSA'),
('GEORGIA','GA','CHATTOOGA','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','CHEROKEE','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','CLARKE','13','Atlanta, GA - AL - NC DMA','Athens, GA MSA'),
('GEORGIA','GA','CLAY','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','CLAYTON','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','CLINCH','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','COBB','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','COFFEE','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','COLQUITT','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','COLUMBIA','13','Augusta, GA - SC DMA','Augusta - Aiken, GA - SC MSA'),
('GEORGIA','GA','COOK','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','COWETA','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','CRAWFORD','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','CRISP','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','DADE','13','Chattanooga, TN - GA - NC DMA','Chattanooga, TN - GA MSA'),
('GEORGIA','GA','DAWSON','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','DECATUR','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','DE KALB','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','DODGE','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','DOOLY','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','DOUGHERTY','13','Albany, GA DMA','Albany, GA MSA'),
('GEORGIA','GA','DOUGLAS','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','EARLY','13','Dothan, AL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','ECHOLS','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','EFFINGHAM','13','Savannah, GA - SC DMA','Savannah, GA MSA'),
('GEORGIA','GA','ELBERT','13','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','EMANUEL','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','EVANS','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','FANNIN','13','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','FAYETTE','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','FLOYD','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','FORSYTH','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','FRANKLIN','13','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','FULTON','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','GILMER','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','GLASCOCK','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','GLYNN','13','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','GORDON','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','GRADY','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','GREENE','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','GWINNETT','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','HABERSHAM','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','HALL','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','HANCOCK','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','HARALSON','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','HARRIS','13','Columbus, GA - AL DMA','Columbus, GA - AL MSA'),
('GEORGIA','GA','HART','13','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','HEARD','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','HENRY','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','HOUSTON','13','Macon, GA DMA','Macon, GA MSA'),
('GEORGIA','GA','IRWIN','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','JACKSON','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','JASPER','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','JEFF DAVIS','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','JEFFERSON','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','JENKINS','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','JOHNSON','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','JONES','13','Macon, GA DMA','Macon, GA MSA'),
('GEORGIA','GA','LAMAR','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','LANIER','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','LAURENS','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','LEE','13','Albany, GA DMA','Albany, GA MSA'),
('GEORGIA','GA','LIBERTY','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','LINCOLN','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','LONG','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','LOWNDES','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','LUMPKIN','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MCDUFFIE','13','Augusta, GA - SC DMA','Augusta - Aiken, GA - SC MSA'),
('GEORGIA','GA','MCINTOSH','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MACON','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MADISON','13','Atlanta, GA - AL - NC DMA','Athens, GA MSA'),
('GEORGIA','GA','MARION','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MERIWETHER','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MILLER','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MITCHELL','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MONROE','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MONTGOMERY','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MORGAN','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MURRAY','13','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','MUSCOGEE','13','Columbus, GA - AL DMA','Columbus, GA - AL MSA'),
('GEORGIA','GA','NEWTON','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','OCONEE','13','Atlanta, GA - AL - NC DMA','Athens, GA MSA'),
('GEORGIA','GA','OGLETHORPE','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','PAULDING','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','PEACH','13','Macon, GA DMA','Macon, GA MSA'),
('GEORGIA','GA','PICKENS','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','PIERCE','13','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','PIKE','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','POLK','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','PULASKI','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)');
