INSERT INTO dma_counties (state, state_abbr, county, state_fips, dma_name, msa) VALUES
('TENNESSEE','TN','PICKETT','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','POLK','47','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','PUTNAM','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','RHEA','47','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','ROANE','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','ROBERTSON','47','Nashville, TN - KY DMA','Nashville, TN MSA'),
('TENNESSEE','TN','RUTHERFORD','47','Nashville, TN - KY DMA','Nashville, TN MSA'),
('TENNESSEE','TN','SCOTT','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','SEQUATCHIE','47','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','SEVIER','47','Knoxville, TN - KY DMA','Knoxville, TN MSA'),
('TENNESSEE','TN','SHELBY','47','Memphis, TN - AR- MS - MO DMA','Memphis, TN - AR - MS MSA'),
('TENNESSEE','TN','SMITH','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','STEWART','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','SULLIVAN','47','Tri - Cities, TN - VA - KY DMA','Johnson City - Kingsport - Bristol, TN - VA MSA'),
('TENNESSEE','TN','SUMNER','47','Nashville, TN - KY DMA','Nashville, TN MSA'),
('TENNESSEE','TN','TIPTON','47','Memphis, TN - AR- MS - MO DMA','Memphis, TN - AR - MS MSA'),
('TENNESSEE','TN','TROUSDALE','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','UNICOI','47','Tri - Cities, TN - VA - KY DMA','Johnson City - Kingsport - Bristol, TN - VA MSA'),
('TENNESSEE','TN','UNION','47','Knoxville, TN - KY DMA','Knoxville, TN MSA'),
('TENNESSEE','TN','VAN BUREN','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','WARREN','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','WASHINGTON','47','Tri - Cities, TN - VA - KY DMA','Johnson City - Kingsport - Bristol, TN - VA MSA'),
('TENNESSEE','TN','WAYNE','47','Huntsville - Decatur - Florence, AL - TN DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','WEAKLEY','47','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','WHITE','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','WILLIAMSON','47','Nashville, TN - KY DMA','Nashville, TN MSA'),
('TENNESSEE','TN','WILSON','47','Nashville, TN - KY DMA','Nashville, TN MSA'),
('TEXAS','TX','ANDERSON','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ANDREWS','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ANGELINA','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ARANSAS','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ARCHER','48','Wichita Falls & Lawton, TX - OK DMA','Wichita Falls, TX MSA'),
('TEXAS','TX','ARMSTRONG','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ATASCOSA','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','AUSTIN','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BAILEY','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BANDERA','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BASTROP','48','Austin, TX DMA','Austin - San Marcos, TX MSA'),
('TEXAS','TX','BAYLOR','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BEE','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BELL','48','Waco - Temple - Bryan, TX DMA','Killeen - Temple, TX MSA'),
('TEXAS','TX','BEXAR','48','San Antonio, TX DMA','San Antonio, TX MSA'),
('TEXAS','TX','BLANCO','48','Austin, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BORDEN','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BOSQUE','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BOWIE','48','Shreveport, LA - AR - OK - TX DMA','Texarkana, TX - Texarkana, AR MSA'),
('TEXAS','TX','BRAZORIA','48','Houston, TX DMA','Brazoria, TX PMSA'),
('TEXAS','TX','BRAZOS','48','Waco - Temple - Bryan, TX DMA','Bryan - College Station, TX MSA'),
('TEXAS','TX','BREWSTER','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BRISCOE','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BROOKS','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BROWN','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BURLESON','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','BURNET','48','Austin, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CALDWELL','48','Austin, TX DMA','Austin - San Marcos, TX MSA'),
('TEXAS','TX','CALHOUN','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CALLAHAN','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CAMERON','48','Harlingen - Weslaco - Brownsville - McAllen, TX DMA','Brownsville - Harlingen - San Benito, TX MSA'),
('TEXAS','TX','CAMP','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CARSON','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CASS','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CASTRO','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CHAMBERS','48','Houston, TX DMA','Houston, TX PMSA'),
('TEXAS','TX','CHEROKEE','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CHILDRESS','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CLAY','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','COCHRAN','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','COKE','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','COLEMAN','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','COLLIN','48','Dallas - Ft. Worth, TX DMA','Dallas, TX PMSA'),
('TEXAS','TX','COLLINGSWORTH','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','COLORADO','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','COMAL','48','San Antonio, TX DMA','San Antonio, TX MSA'),
('TEXAS','TX','COMANCHE','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CONCHO','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','COOKE','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CORYELL','48','Waco - Temple - Bryan, TX DMA','Killeen - Temple, TX MSA'),
('TEXAS','TX','COTTLE','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CRANE','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CROCKETT','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CROSBY','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','CULBERSON','48','El Paso, TX - NM DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DALLAM','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DALLAS','48','Dallas - Ft. Worth, TX DMA','Dallas, TX PMSA'),
('TEXAS','TX','DAWSON','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DEAF SMITH','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DELTA','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DENTON','48','Dallas - Ft. Worth, TX DMA','Dallas, TX PMSA'),
('TEXAS','TX','DE WITT','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DICKENS','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DIMMIT','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DONLEY','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','DUVAL','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','EASTLAND','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ECTOR','48','Odessa - Midland, TX DMA','Odessa - Midland, TX MSA'),
('TEXAS','TX','EDWARDS','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ELLIS','48','Dallas - Ft. Worth, TX DMA','Dallas, TX PMSA'),
('TEXAS','TX','EL PASO','48','El Paso, TX - NM DMA','El Paso, TX MSA'),
('TEXAS','TX','ERATH','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FALLS','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FANNIN','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FAYETTE','48','Austin, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FISHER','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FLOYD','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FOARD','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FORT BEND','48','Houston, TX DMA','Houston, TX PMSA'),
('TEXAS','TX','FRANKLIN','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FREESTONE','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','FRIO','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GAINES','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GALVESTON','48','Houston, TX DMA','Galveston - Texas City, TX PMSA'),
('TEXAS','TX','GARZA','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GILLESPIE','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GLASSCOCK','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GOLIAD','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GONZALES','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GRAY','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GRAYSON','48','Sherman - Ada, OK - TX DMA','Sherman - Denison, TX MSA'),
('TEXAS','TX','GREGG','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Longview - Marshall, TX MSA'),
('TEXAS','TX','GRIMES','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','GUADALUPE','48','San Antonio, TX DMA','San Antonio, TX MSA'),
('TEXAS','TX','HALE','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HALL','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HAMILTON','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HANSFORD','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HARDEMAN','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HARDIN','48','Beaumont - Port Arthur, TX DMA','Beaumont - Port Arthur, TX MSA'),
('TEXAS','TX','HARRIS','48','Houston, TX DMA','Houston, TX PMSA'),
('TEXAS','TX','HARRISON','48','Shreveport, LA - AR - OK - TX DMA','Longview - Marshall, TX MSA'),
('TEXAS','TX','HARTLEY','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HASKELL','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HAYS','48','Austin, TX DMA','Austin - San Marcos, TX MSA'),
('TEXAS','TX','HEMPHILL','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HENDERSON','48','Dallas - Ft. Worth, TX DMA','Dallas, TX PMSA'),
('TEXAS','TX','HIDALGO','48','Harlingen - Weslaco - Brownsville - McAllen, TX DMA','McAllen - Edinburg - Mission, TX MSA'),
('TEXAS','TX','HILL','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HOCKLEY','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HOOD','48','Dallas - Ft. Worth, TX DMA','Fort Worth - Arlington, TX PMSA'),
('TEXAS','TX','HOPKINS','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HOUSTON','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HOWARD','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HUDSPETH','48','El Paso, TX - NM DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','HUNT','48','Dallas - Ft. Worth, TX DMA','Dallas, TX PMSA'),
('TEXAS','TX','HUTCHINSON','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','IRION','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','JACK','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','JACKSON','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','JASPER','48','Beaumont - Port Arthur, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','JEFF DAVIS','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','JEFFERSON','48','Beaumont - Port Arthur, TX DMA','Beaumont - Port Arthur, TX MSA'),
('TEXAS','TX','JIM HOGG','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','JIM WELLS','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','JOHNSON','48','Dallas - Ft. Worth, TX DMA','Fort Worth - Arlington, TX PMSA'),
('TEXAS','TX','JONES','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KARNES','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KAUFMAN','48','Dallas - Ft. Worth, TX DMA','Dallas, TX PMSA'),
('TEXAS','TX','KENDALL','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KENEDY','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KENT','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KERR','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KIMBLE','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KING','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KINNEY','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KLEBERG','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','KNOX','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LAMAR','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LAMB','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LAMPASAS','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LA SALLE','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LAVACA','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LEE','48','Austin, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LEON','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LIBERTY','48','Houston, TX DMA','Houston, TX PMSA'),
('TEXAS','TX','LIMESTONE','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LIPSCOMB','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LIVE OAK','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LLANO','48','Austin, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LOVING','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','LUBBOCK','48','Lubbock, TX DMA','Lubbock, TX MSA'),
('TEXAS','TX','LYNN','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MCCULLOCH','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MCLENNAN','48','Waco - Temple - Bryan, TX DMA','Waco, TX MSA'),
('TEXAS','TX','MCMULLEN','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MADISON','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MARION','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MARTIN','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MASON','48','Austin, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MATAGORDA','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MAVERICK','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MEDINA','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MENARD','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MIDLAND','48','Odessa - Midland, TX DMA','Odessa - Midland, TX MSA'),
('TEXAS','TX','MILAM','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MILLS','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MITCHELL','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MONTAGUE','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MONTGOMERY','48','Houston, TX DMA','Houston, TX PMSA'),
('TEXAS','TX','MOORE','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MORRIS','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','MOTLEY','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','NACOGDOCHES','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','NAVARRO','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','NEWTON','48','Beaumont - Port Arthur, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','NOLAN','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','NUECES','48','Corpus Christi, TX DMA','Corpus Christi, TX MSA'),
('TEXAS','TX','OCHILTREE','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','OLDHAM','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ORANGE','48','Beaumont - Port Arthur, TX DMA','Beaumont - Port Arthur, TX MSA'),
('TEXAS','TX','PALO PINTO','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','PANOLA','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','PARKER','48','Dallas - Ft. Worth, TX DMA','Fort Worth - Arlington, TX PMSA'),
('TEXAS','TX','PARMER','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','PECOS','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','POLK','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','POTTER','48','Amarillo, TX -NM - OK DMA','Amarillo, TX MSA'),
('TEXAS','TX','PRESIDIO','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','RAINS','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','RANDALL','48','Amarillo, TX -NM - OK DMA','Amarillo, TX MSA'),
('TEXAS','TX','REAGAN','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','REAL','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','RED RIVER','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','REEVES','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','REFUGIO','48','Corpus Christi, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ROBERTS','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ROBERTSON','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ROCKWALL','48','Dallas - Ft. Worth, TX DMA','Dallas, TX PMSA'),
('TEXAS','TX','RUNNELS','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','RUSK','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SABINE','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SAN AUGUSTINE','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SAN JACINTO','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SAN PATRICIO','48','Corpus Christi, TX DMA','Corpus Christi, TX MSA'),
('TEXAS','TX','SAN SABA','48','Waco - Temple - Bryan, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SCHLEICHER','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SCURRY','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SHACKELFORD','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SHELBY','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SHERMAN','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SMITH','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Tyler, TX MSA'),
('TEXAS','TX','SOMERVELL','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','STARR','48','Harlingen - Weslaco - Brownsville - McAllen, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','STEPHENS','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','STERLING','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','STONEWALL','48','Abilene - Sweetwater, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SUTTON','48','San Angelo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','SWISHER','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','TARRANT','48','Dallas - Ft. Worth, TX DMA','Fort Worth - Arlington, TX PMSA'),
('TEXAS','TX','TAYLOR','48','Abilene - Sweetwater, TX DMA','Abilene, TX MSA'),
('TEXAS','TX','TERRELL','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','TERRY','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','THROCKMORTON','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','TITUS','48','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','TOM GREEN','48','San Angelo, TX DMA','San Angelo, TX MSA'),
('TEXAS','TX','TRAVIS','48','Austin, TX DMA','Austin - San Marcos, TX MSA'),
('TEXAS','TX','TRINITY','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','TYLER','48','Beaumont - Port Arthur, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','UPSHUR','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Longview - Marshall, TX MSA'),
('TEXAS','TX','UPTON','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','UVALDE','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','VAL VERDE','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','VAN ZANDT','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','VICTORIA','48','Victoria, TX DMA','Victoria, TX MSA'),
('TEXAS','TX','WALKER','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WALLER','48','Houston, TX DMA','Houston, TX PMSA'),
('TEXAS','TX','WARD','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WASHINGTON','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WEBB','48','Laredo, TX DMA','Laredo, TX MSA'),
('TEXAS','TX','WHARTON','48','Houston, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WHEELER','48','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WICHITA','48','Wichita Falls & Lawton, TX - OK DMA','Wichita Falls, TX MSA'),
('TEXAS','TX','WILBARGER','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WILLACY','48','Harlingen - Weslaco - Brownsville - McAllen, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WILLIAMSON','48','Austin, TX DMA','Austin - San Marcos, TX MSA'),
('TEXAS','TX','WILSON','48','San Antonio, TX DMA','San Antonio, TX MSA'),
('TEXAS','TX','WINKLER','48','Odessa - Midland, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WISE','48','Dallas - Ft. Worth, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','WOOD','48','Tyler - Longview (Lufkin&Nacogdoches), TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','YOAKUM','48','Lubbock, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','YOUNG','48','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ZAPATA','48','Laredo, TX DMA','Not Assigned to Metro Area (NAM)'),
('TEXAS','TX','ZAVALA','48','San Antonio, TX DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','BEAVER','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','BOX ELDER','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','CACHE','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','CARBON','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','DAGGETT','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','DAVIS','49','Salt Lake City, UT - ID - WY DMA','Salt Lake City - Ogden, UT MSA'),
('UTAH','UT','DUCHESNE','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','EMERY','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','GARFIELD','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','GRAND','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','IRON','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','JUAB','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','KANE','49','Salt Lake City, UT - ID - WY DMA','Flagstaff, AZ - UT MSA'),
('UTAH','UT','MILLARD','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','MORGAN','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','PIUTE','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','RICH','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','SALT LAKE','49','Salt Lake City, UT - ID - WY DMA','Salt Lake City - Ogden, UT MSA'),
('UTAH','UT','SAN JUAN','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','SANPETE','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','SEVIER','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','SUMMIT','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','TOOELE','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','UINTAH','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','UTAH','49','Salt Lake City, UT - ID - WY DMA','Provo - Orem, UT MSA'),
('UTAH','UT','WASATCH','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','WASHINGTON','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','WAYNE','49','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('UTAH','UT','WEBER','49','Salt Lake City, UT - ID - WY DMA','Salt Lake City - Ogden, UT MSA'),
('VERMONT','VT','ADDISON','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','BENNINGTON','50','Albany - Schenectady - Troy, NY - MA - VT DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','CALEDONIA','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','CHITTENDEN','50','Burlington, VT - Plattsburgh, NY DMA','Burlington, VT NECMA'),
('VERMONT','VT','ESSEX','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','FRANKLIN','50','Burlington, VT - Plattsburgh, NY DMA','Burlington, VT NECMA'),
('VERMONT','VT','GRAND ISLE','50','Burlington, VT - Plattsburgh, NY DMA','Burlington, VT NECMA'),
('VERMONT','VT','LAMOILLE','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','ORANGE','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','ORLEANS','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','RUTLAND','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','WASHINGTON','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','WINDHAM','50','Boston, MA - NH DMA','Not Assigned to Metro Area (NAM)'),
('VERMONT','VT','WINDSOR','50','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','ACCOMACK','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','ALBEMARLE','51','Charlottesville, VA DMA','Charlottesville, VA MSA'),
('VIRGINIA','VA','ALLEGHANY','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','AMELIA','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','AMHERST','51','Roanoke - Lynchburg, VA - WV DMA','Lynchburg, VA MSA'),
('VIRGINIA','VA','APPOMATTOX','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','ARLINGTON','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','AUGUSTA','51','Harrisonburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','BATH','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','BEDFORD','51','Roanoke - Lynchburg, VA - WV DMA','Lynchburg, VA MSA'),
('VIRGINIA','VA','BLAND','51','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','BOTETOURT','51','Roanoke - Lynchburg, VA - WV DMA','Roanoke, VA MSA'),
('VIRGINIA','VA','BRUNSWICK','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','BUCHANAN','51','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','BUCKINGHAM','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','CAMPBELL','51','Roanoke - Lynchburg, VA - WV DMA','Lynchburg, VA MSA'),
('VIRGINIA','VA','CAROLINE','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','CARROLL','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','CHARLES CITY','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','CHARLOTTE','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','CHESTERFIELD','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','CLARKE','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','CRAIG','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','CULPEPER','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','CUMBERLAND','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','DICKENSON','51','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','DINWIDDIE','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','ESSEX','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','FAIRFAX','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','FAUQUIER','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','FLOYD','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','FLUVANNA','51','Richmond - Petersburg, VA DMA','Charlottesville, VA MSA'),
('VIRGINIA','VA','FRANKLIN','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','FREDERICK','51','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','GILES','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','GLOUCESTER','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','GOOCHLAND','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','GRAYSON','51','Greensboro - H.Point - W.Salem, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','GREENE','51','Charlottesville, VA DMA','Charlottesville, VA MSA'),
('VIRGINIA','VA','GREENSVILLE','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','HALIFAX','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','HANOVER','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','HENRICO','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','HENRY','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','HIGHLAND','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','ISLE OF WIGHT','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','JAMES CITY','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','KING AND QUEEN','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','KING GEORGE','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','KING WILLIAM','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','LANCASTER','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','LEE','51','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','LOUDOUN','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','LOUISA','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','LUNENBURG','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','MADISON','51','Charlottesville, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','MATHEWS','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','MECKLENBURG','51','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','MIDDLESEX','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','MONTGOMERY','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','NELSON','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','NEW KENT','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','NORTHAMPTON','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','NORTHUMBERLAND','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','NOTTOWAY','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','ORANGE','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','PAGE','51','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','PATRICK','51','Greensboro - H.Point - W.Salem, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','PITTSYLVANIA','51','Roanoke - Lynchburg, VA - WV DMA','Danville, VA MSA'),
('VIRGINIA','VA','POWHATAN','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','PRINCE EDWARD','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','PRINCE GEORGE','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','PRINCE WILLIAM','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','PULASKI','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','RAPPAHANNOCK','51','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','RICHMOND','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','ROANOKE','51','Roanoke - Lynchburg, VA - WV DMA','Roanoke, VA MSA'),
('VIRGINIA','VA','ROCKBRIDGE','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','ROCKINGHAM','51','Harrisonburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','RUSSELL','51','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','SCOTT','51','Tri - Cities, TN - VA - KY DMA','Johnson City - Kingsport - Bristol, TN - VA MSA'),
('VIRGINIA','VA','SHENANDOAH','51','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','SMYTH','51','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','SOUTHAMPTON','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','SPOTSYLVANIA','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','STAFFORD','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','SURRY','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','SUSSEX','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','TAZEWELL','51','Bluefield - Beckley - Oak Hill, WV - VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','WARREN','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','WASHINGTON','51','Tri - Cities, TN - VA - KY DMA','Johnson City - Kingsport - Bristol, TN - VA MSA'),
('VIRGINIA','VA','WESTMORELAND','51','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','WISE','51','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','WYTHE','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','YORK','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','ALEXANDRIA','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','BEDFORD CITY','51','Roanoke - Lynchburg, VA - WV DMA','Lynchburg, VA MSA'),
('VIRGINIA','VA','BRISTOL','51','Tri - Cities, TN - VA - KY DMA','Johnson City - Kingsport - Bristol, TN - VA MSA'),
('VIRGINIA','VA','BUENA VISTA','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','CHARLOTTESVILLE','51','Charlottesville, VA DMA','Charlottesville, VA MSA'),
('VIRGINIA','VA','CHESAPEAKE','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','CLIFTON FORGE','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','COLONIAL HEIGHTS','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','COVINGTON','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','DANVILLE','51','Roanoke - Lynchburg, VA - WV DMA','Danville, VA MSA'),
('VIRGINIA','VA','EMPORIA','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','FAIRFAX CITY','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','FALLS CHURCH','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','FRANKLIN CITY','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','FREDERICKSBURG','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','GALAX','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','HAMPTON','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','HARRISONBURG','51','Harrisonburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','HOPEWELL','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','LEXINGTON','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','LYNCHBURG','51','Roanoke - Lynchburg, VA - WV DMA','Lynchburg, VA MSA'),
('VIRGINIA','VA','MANASSAS','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','MANASSAS PARK','51','Washington, DC - MD - PA - VA - WV DMA','Washington, DC - MD - VA - WV PMSA'),
('VIRGINIA','VA','MARTINSVILLE','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','NEWPORT NEWS','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','NORFOLK','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','NORTON','51','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','PETERSBURG','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','POQUOSON','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','PORTSMOUTH','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','RADFORD','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','RICHMOND CITY','51','Richmond - Petersburg, VA DMA','Richmond - Petersburg, VA MSA'),
('VIRGINIA','VA','ROANOKE CITY','51','Roanoke - Lynchburg, VA - WV DMA','Roanoke, VA MSA'),
('VIRGINIA','VA','SALEM','51','Roanoke - Lynchburg, VA - WV DMA','Roanoke, VA MSA'),
('VIRGINIA','VA','SOUTH BOSTON','51','Roanoke - Lynchburg, VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','STAUNTON','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','SUFFOLK','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','VIRGINIA BEACH','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','WAYNESBORO','51','Richmond - Petersburg, VA DMA','Not Assigned to Metro Area (NAM)'),
('VIRGINIA','VA','WILLIAMSBURG','51','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('VIRGINIA','VA','WINCHESTER','51','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','CLARK','53','Portland, OR - WA DMA','Portland - Vancouver, OR - WA PMSA'),
('WASHINGTON','WA','COWLITZ','53','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','KLICKITAT','53','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','SKAMANIA','53','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','WAHKIAKUM','53','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','CHELAN','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','CLALLAM','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','DOUGLAS','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','GRAYS HARBOR','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','ISLAND','53','Seattle - Tacoma, WA DMA','Seattle - Bellevue - Everett, WA PMSA'),
('WASHINGTON','WA','JEFFERSON','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','KING','53','Seattle - Tacoma, WA DMA','Seattle - Bellevue - Everett, WA PMSA'),
('WASHINGTON','WA','KITSAP','53','Seattle - Tacoma, WA DMA','Bremerton, WA PMSA'),
('WASHINGTON','WA','LEWIS','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','MASON','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','PACIFIC','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','PIERCE','53','Seattle - Tacoma, WA DMA','Tacoma, WA PMSA'),
('WASHINGTON','WA','SAN JUAN','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','SKAGIT','53','Seattle - Tacoma, WA DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','SNOHOMISH','53','Seattle - Tacoma, WA DMA','Seattle - Bellevue - Everett, WA PMSA'),
('WASHINGTON','WA','THURSTON','53','Seattle - Tacoma, WA DMA','Olympia, WA PMSA'),
('WASHINGTON','WA','WHATCOM','53','Seattle - Tacoma, WA DMA','Bellingham, WA MSA'),
('WASHINGTON','WA','FERRY','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','LINCOLN','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','OKANOGAN','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','PEND OREILLE','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','SPOKANE','53','Spokane, WA - ID - MT - OR DMA','Spokane, WA MSA'),
('WASHINGTON','WA','STEVENS','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','ADAMS','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','ASOTIN','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','BENTON','53','Yakima - Pasco - Richland - Kennewick, WA - OR DMA','Richland - Kennewick - Pasco, WA MSA'),
('WASHINGTON','WA','COLUMBIA','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','FRANKLIN','53','Yakima - Pasco - Richland - Kennewick, WA - OR DMA','Richland - Kennewick - Pasco, WA MSA'),
('WASHINGTON','WA','GARFIELD','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','GRANT','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','KITTITAS','53','Yakima - Pasco - Richland - Kennewick, WA - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','WALLA WALLA','53','Yakima - Pasco - Richland - Kennewick, WA - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','WHITMAN','53','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('WASHINGTON','WA','YAKIMA','53','Yakima - Pasco - Richland - Kennewick, WA - OR DMA','Yakima, WA MSA'),
('WEST VIRGINIA','WV','BARBOUR','54','Clarksburg - Weston, WV DMA','Not Assigned to Metro Area (NAM)');
