INSERT INTO dma_counties (state, state_abbr, county, state_fips, dma_name, msa) VALUES
('NORTH DAKOTA','ND','EMMONS','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','FOSTER','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','GOLDEN VALLEY','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','GRAND FORKS','38','Fargo - Valley City, ND - MN DMA','Grand Forks, ND - MN MSA'),
('NORTH DAKOTA','ND','GRANT','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','GRIGGS','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','HETTINGER','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','KIDDER','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','LA MOURE','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','LOGAN','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','MCHENRY','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','MCINTOSH','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','MCKENZIE','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','MCLEAN','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','MERCER','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','MORTON','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Bismarck, ND MSA'),
('NORTH DAKOTA','ND','MOUNTRAIL','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','NELSON','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','OLIVER','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','PEMBINA','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','PIERCE','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','RAMSEY','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','RANSOM','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','RENVILLE','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','RICHLAND','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','ROLETTE','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','SARGENT','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','SHERIDAN','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','SIOUX','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','SLOPE','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','STARK','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','STEELE','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','STUTSMAN','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','TOWNER','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','TRAILL','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','WALSH','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','WARD','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','WELLS','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','ADAMS','39','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','ALLEN','39','Lima, OH DMA','Lima, OH MSA'),
('OHIO','OH','ASHLAND','39','Cleveland, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','ASHTABULA','39','Cleveland, OH DMA','Cleveland - Lorain - Elyria, OH PMSA'),
('OHIO','OH','ATHENS','39','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','AUGLAIZE','39','Dayton, OH - IN DMA','Lima, OH MSA'),
('OHIO','OH','BELMONT','39','Wheeling - Steubenville, WV - OH DMA','Wheeling, WV - OH MSA'),
('OHIO','OH','BROWN','39','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('OHIO','OH','BUTLER','39','Cincinnati, OH -IN - KY DMA','Hamilton - Middletown, OH PMSA'),
('OHIO','OH','CARROLL','39','Cleveland, OH DMA','Canton - Massillon, OH MSA'),
('OHIO','OH','CHAMPAIGN','39','Dayton, OH - IN DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','CLARK','39','Dayton, OH - IN DMA','Dayton - Springfield, OH MSA'),
('OHIO','OH','CLERMONT','39','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('OHIO','OH','CLINTON','39','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','COLUMBIANA','39','Youngstown, OH - PA DMA','Youngstown - Warren, OH MSA'),
('OHIO','OH','COSHOCTON','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','CRAWFORD','39','Columbus, OH DMA','Mansfield, OH MSA'),
('OHIO','OH','CUYAHOGA','39','Cleveland, OH DMA','Cleveland - Lorain - Elyria, OH PMSA'),
('OHIO','OH','DARKE','39','Dayton, OH - IN DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','DEFIANCE','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','DELAWARE','39','Columbus, OH DMA','Columbus, OH MSA'),
('OHIO','OH','ERIE','39','Cleveland, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','FAIRFIELD','39','Columbus, OH DMA','Columbus, OH MSA'),
('OHIO','OH','FAYETTE','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','FRANKLIN','39','Columbus, OH DMA','Columbus, OH MSA'),
('OHIO','OH','FULTON','39','Toledo, OH - MI DMA','Toledo, OH MSA'),
('OHIO','OH','GALLIA','39','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','GEAUGA','39','Cleveland, OH DMA','Cleveland - Lorain - Elyria, OH PMSA'),
('OHIO','OH','GREENE','39','Dayton, OH - IN DMA','Dayton - Springfield, OH MSA'),
('OHIO','OH','GUERNSEY','39','Wheeling - Steubenville, WV - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','HAMILTON','39','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('OHIO','OH','HANCOCK','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','HARDIN','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','HARRISON','39','Wheeling - Steubenville, WV - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','HENRY','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','HIGHLAND','39','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','HOCKING','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','HOLMES','39','Cleveland, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','HURON','39','Cleveland, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','JACKSON','39','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','JEFFERSON','39','Wheeling - Steubenville, WV - OH DMA','Steubenville - Weirton, OH - WV MSA'),
('OHIO','OH','KNOX','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','LAKE','39','Cleveland, OH DMA','Cleveland - Lorain - Elyria, OH PMSA'),
('OHIO','OH','LAWRENCE','39','Charleston - Huntington, WV - KY - OH DMA','Huntington - Ashland, WV - KY - OH MSA'),
('OHIO','OH','LICKING','39','Columbus, OH DMA','Columbus, OH MSA'),
('OHIO','OH','LOGAN','39','Dayton, OH - IN DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','LORAIN','39','Cleveland, OH DMA','Cleveland - Lorain - Elyria, OH PMSA'),
('OHIO','OH','LUCAS','39','Toledo, OH - MI DMA','Toledo, OH MSA'),
('OHIO','OH','MADISON','39','Columbus, OH DMA','Columbus, OH MSA'),
('OHIO','OH','MAHONING','39','Youngstown, OH - PA DMA','Youngstown - Warren, OH MSA'),
('OHIO','OH','MARION','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','MEDINA','39','Cleveland, OH DMA','Cleveland - Lorain - Elyria, OH PMSA'),
('OHIO','OH','MEIGS','39','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','MERCER','39','Dayton, OH - IN DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','MIAMI','39','Dayton, OH - IN DMA','Dayton - Springfield, OH MSA'),
('OHIO','OH','MONROE','39','Wheeling - Steubenville, WV - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','MONTGOMERY','39','Dayton, OH - IN DMA','Dayton - Springfield, OH MSA'),
('OHIO','OH','MORGAN','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','MORROW','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','MUSKINGUM','39','Zanesville, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','NOBLE','39','Wheeling - Steubenville, WV - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','OTTAWA','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','PAULDING','39','Ft. Wayne, IN - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','PERRY','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','PICKAWAY','39','Columbus, OH DMA','Columbus, OH MSA'),
('OHIO','OH','PIKE','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','PORTAGE','39','Cleveland, OH DMA','Akron, OH PMSA'),
('OHIO','OH','PREBLE','39','Dayton, OH - IN DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','PUTNAM','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','RICHLAND','39','Cleveland, OH DMA','Mansfield, OH MSA'),
('OHIO','OH','ROSS','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','SANDUSKY','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','SCIOTO','39','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','SENECA','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','SHELBY','39','Dayton, OH - IN DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','STARK','39','Cleveland, OH DMA','Canton - Massillon, OH MSA'),
('OHIO','OH','SUMMIT','39','Cleveland, OH DMA','Akron, OH PMSA'),
('OHIO','OH','TRUMBULL','39','Youngstown, OH - PA DMA','Youngstown - Warren, OH MSA'),
('OHIO','OH','TUSCARAWAS','39','Cleveland, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','UNION','39','Columbus, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','VAN WERT','39','Ft. Wayne, IN - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','VINTON','39','Charleston - Huntington, WV - KY - OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','WARREN','39','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('OHIO','OH','WASHINGTON','39','Parkersburg, WV - OH DMA','Parkersburg - Marietta, WV - OH MSA'),
('OHIO','OH','WAYNE','39','Cleveland, OH DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','WILLIAMS','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OHIO','OH','WOOD','39','Toledo, OH - MI DMA','Toledo, OH MSA'),
('OHIO','OH','WYANDOT','39','Toledo, OH - MI DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','ADAIR','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','ALFALFA','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','ATOKA','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','BEAVER','40','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','BECKHAM','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','BLAINE','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','BRYAN','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','CADDO','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','CANADIAN','40','Oklahoma City, OK DMA','Oklahoma City, OK MSA'),
('OKLAHOMA','OK','CARTER','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','CHEROKEE','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','CHOCTAW','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','CIMARRON','40','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','CLEVELAND','40','Oklahoma City, OK DMA','Oklahoma City, OK MSA'),
('OKLAHOMA','OK','COAL','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','COMANCHE','40','Wichita Falls & Lawton, TX - OK DMA','Lawton, OK MSA'),
('OKLAHOMA','OK','COTTON','40','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','CRAIG','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','CREEK','40','Tulsa, OK - KS DMA','Tulsa, OK MSA'),
('OKLAHOMA','OK','CUSTER','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','DELAWARE','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','DEWEY','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','ELLIS','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','GARFIELD','40','Oklahoma City, OK DMA','Enid, OK MSA'),
('OKLAHOMA','OK','GARVIN','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','GRADY','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','GRANT','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','GREER','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','HARMON','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','HARPER','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','HASKELL','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','HUGHES','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','JACKSON','40','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','JEFFERSON','40','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','JOHNSTON','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','KAY','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','KINGFISHER','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','KIOWA','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','LATIMER','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','LE FLORE','40','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','LINCOLN','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','LOGAN','40','Oklahoma City, OK DMA','Oklahoma City, OK MSA'),
('OKLAHOMA','OK','LOVE','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','MCCLAIN','40','Oklahoma City, OK DMA','Oklahoma City, OK MSA'),
('OKLAHOMA','OK','MCCURTAIN','40','Shreveport, LA - AR - OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','MCINTOSH','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','MAJOR','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','MARSHALL','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','MAYES','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','MURRAY','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','MUSKOGEE','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','NOBLE','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','NOWATA','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','OKFUSKEE','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','OKLAHOMA','40','Oklahoma City, OK DMA','Oklahoma City, OK MSA'),
('OKLAHOMA','OK','OKMULGEE','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','OSAGE','40','Tulsa, OK - KS DMA','Tulsa, OK MSA'),
('OKLAHOMA','OK','OTTAWA','40','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','PAWNEE','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','PAYNE','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','PITTSBURG','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','PONTOTOC','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','POTTAWATOMIE','40','Oklahoma City, OK DMA','Oklahoma City, OK MSA'),
('OKLAHOMA','OK','PUSHMATAHA','40','Sherman - Ada, OK - TX DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','ROGER MILLS','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','ROGERS','40','Tulsa, OK - KS DMA','Tulsa, OK MSA'),
('OKLAHOMA','OK','SEMINOLE','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','SEQUOYAH','40','Ft. Smith - Fay - Springdale - Rogers, AR - OK DMA','Fort Smith, AR - OK MSA'),
('OKLAHOMA','OK','STEPHENS','40','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','TEXAS','40','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','TILLMAN','40','Wichita Falls & Lawton, TX - OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','TULSA','40','Tulsa, OK - KS DMA','Tulsa, OK MSA'),
('OKLAHOMA','OK','WAGONER','40','Tulsa, OK - KS DMA','Tulsa, OK MSA'),
('OKLAHOMA','OK','WASHINGTON','40','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','WASHITA','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','WOODS','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OKLAHOMA','OK','WOODWARD','40','Oklahoma City, OK DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','BAKER','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','BENTON','41','Eugene, OR DMA','Corvallis, OR MSA'),
('OREGON','OR','CLACKAMAS','41','Portland, OR - WA DMA','Portland - Vancouver, OR - WA PMSA'),
('OREGON','OR','CLATSOP','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','COLUMBIA','41','Portland, OR - WA DMA','Portland - Vancouver, OR - WA PMSA'),
('OREGON','OR','COOS','41','Eugene, OR DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','CROOK','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','CURRY','41','Medford - Klamath Falls, OR - CA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','DESCHUTES','41','Bend, OR DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','DOUGLAS','41','Eugene, OR DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','GILLIAM','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','GRANT','41','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','HARNEY','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','HOOD RIVER','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','JACKSON','41','Medford - Klamath Falls, OR - CA DMA','Medford - Ashland, OR MSA'),
('OREGON','OR','JEFFERSON','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','JOSEPHINE','41','Medford - Klamath Falls, OR - CA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','KLAMATH','41','Medford - Klamath Falls, OR - CA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','LAKE','41','Medford - Klamath Falls, OR - CA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','LANE','41','Eugene, OR DMA','Eugene - Springfield, OR MSA'),
('OREGON','OR','LINCOLN','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','LINN','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','MALHEUR','41','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','MARION','41','Portland, OR - WA DMA','Salem, OR PMSA'),
('OREGON','OR','MORROW','41','Yakima - Pasco - Richland - Kennewick, WA - OR DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','MULTNOMAH','41','Portland, OR - WA DMA','Portland - Vancouver, OR - WA PMSA'),
('OREGON','OR','POLK','41','Portland, OR - WA DMA','Salem, OR PMSA'),
('OREGON','OR','SHERMAN','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','TILLAMOOK','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','UMATILLA','41','Yakima - Pasco - Richland - Kennewick, WA - OR DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','UNION','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','WALLOWA','41','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','WASCO','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','WASHINGTON','41','Portland, OR - WA DMA','Portland - Vancouver, OR - WA PMSA'),
('OREGON','OR','WHEELER','41','Portland, OR - WA DMA','Not Assigned to Metro Area (NAM)'),
('OREGON','OR','YAMHILL','41','Portland, OR - WA DMA','Portland - Vancouver, OR - WA PMSA'),
('PENNSYLVANIA','PA','ADAMS','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','ALLEGHENY','42','Pittsburgh, PA - MD- WV DMA','Pittsburgh, PA MSA'),
('PENNSYLVANIA','PA','ARMSTRONG','42','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','BEAVER','42','Pittsburgh, PA - MD- WV DMA','Pittsburgh, PA MSA'),
('PENNSYLVANIA','PA','BEDFORD','42','Johnstown - Altoona, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','BERKS','42','Philadelphia, PA - DE - NJ DMA','Reading, PA MSA'),
('PENNSYLVANIA','PA','BLAIR','42','Johnstown - Altoona, PA DMA','Altoona, PA MSA'),
('PENNSYLVANIA','PA','BRADFORD','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','BUCKS','42','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('PENNSYLVANIA','PA','BUTLER','42','Pittsburgh, PA - MD- WV DMA','Pittsburgh, PA MSA'),
('PENNSYLVANIA','PA','CAMBRIA','42','Johnstown - Altoona, PA DMA','Johnstown, PA MSA'),
('PENNSYLVANIA','PA','CAMERON','42','Johnstown - Altoona, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','CARBON','42','Wilkes Barre - Scranton, PA DMA','Allentown - Bethlehem - Easton, PA MSA'),
('PENNSYLVANIA','PA','CENTRE','42','Johnstown - Altoona, PA DMA','State College, PA MSA'),
('PENNSYLVANIA','PA','CHESTER','42','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('PENNSYLVANIA','PA','CLARION','42','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','CLEARFIELD','42','Johnstown - Altoona, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','CLINTON','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','COLUMBIA','42','Wilkes Barre - Scranton, PA DMA','Scranton - Wilkes-Barre - Hazleton, PA MSA'),
('PENNSYLVANIA','PA','CRAWFORD','42','Erie, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','CUMBERLAND','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','Harrisburg - Lebanon - Carlisle, PA MSA'),
('PENNSYLVANIA','PA','DAUPHIN','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','Harrisburg - Lebanon - Carlisle, PA MSA'),
('PENNSYLVANIA','PA','DELAWARE','42','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('PENNSYLVANIA','PA','ELK','42','Johnstown - Altoona, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','ERIE','42','Erie, PA DMA','Erie, PA MSA'),
('PENNSYLVANIA','PA','FAYETTE','42','Pittsburgh, PA - MD- WV DMA','Pittsburgh, PA MSA'),
('PENNSYLVANIA','PA','FOREST','42','Johnstown - Altoona, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','FRANKLIN','42','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','FULTON','42','Washington, DC - MD - PA - VA - WV DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','GREENE','42','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','HUNTINGDON','42','Johnstown - Altoona, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','INDIANA','42','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','JEFFERSON','42','Johnstown - Altoona, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','JUNIATA','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','LACKAWANNA','42','Wilkes Barre - Scranton, PA DMA','Scranton - Wilkes-Barre - Hazleton, PA MSA'),
('PENNSYLVANIA','PA','LANCASTER','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','Lancaster, PA MSA'),
('PENNSYLVANIA','PA','LAWRENCE','42','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','LEBANON','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','Harrisburg - Lebanon - Carlisle, PA MSA'),
('PENNSYLVANIA','PA','LEHIGH','42','Philadelphia, PA - DE - NJ DMA','Allentown - Bethlehem - Easton, PA MSA'),
('PENNSYLVANIA','PA','LUZERNE','42','Wilkes Barre - Scranton, PA DMA','Scranton - Wilkes-Barre - Hazleton, PA MSA'),
('PENNSYLVANIA','PA','LYCOMING','42','Wilkes Barre - Scranton, PA DMA','Williamsport, PA MSA'),
('PENNSYLVANIA','PA','MCKEAN','42','Buffalo, NY - PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','MERCER','42','Youngstown, OH - PA DMA','Sharon, PA MSA'),
('PENNSYLVANIA','PA','MIFFLIN','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','MONROE','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','MONTGOMERY','42','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('PENNSYLVANIA','PA','MONTOUR','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','NORTHAMPTON','42','Philadelphia, PA - DE - NJ DMA','Allentown - Bethlehem - Easton, PA MSA'),
('PENNSYLVANIA','PA','NORTHUMBERLAND','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','PERRY','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','Harrisburg - Lebanon - Carlisle, PA MSA'),
('PENNSYLVANIA','PA','PHILADELPHIA','42','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('PENNSYLVANIA','PA','PIKE','42','New York, NY - CT - NJ - PA DMA','Newburgh, NY - PA PMSA'),
('PENNSYLVANIA','PA','POTTER','42','Buffalo, NY - PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','SCHUYLKILL','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','SNYDER','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','SOMERSET','42','Johnstown - Altoona, PA DMA','Johnstown, PA MSA'),
('PENNSYLVANIA','PA','SULLIVAN','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','SUSQUEHANNA','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','TIOGA','42','Elmira, NY - PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','UNION','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','VENANGO','42','Pittsburgh, PA - MD- WV DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','WARREN','42','Erie, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','WASHINGTON','42','Pittsburgh, PA - MD- WV DMA','Pittsburgh, PA MSA'),
('PENNSYLVANIA','PA','WAYNE','42','Wilkes Barre - Scranton, PA DMA','Not Assigned to Metro Area (NAM)'),
('PENNSYLVANIA','PA','WESTMORELAND','42','Pittsburgh, PA - MD- WV DMA','Pittsburgh, PA MSA'),
('PENNSYLVANIA','PA','WYOMING','42','Wilkes Barre - Scranton, PA DMA','Scranton - Wilkes-Barre - Hazleton, PA MSA'),
('PENNSYLVANIA','PA','YORK','42','Harrisburg - Lancaster - Lebanon - York, PA DMA','York, PA MSA'),
('RHODE ISLAND','RI','BRISTOL','44','Providence, RI - New Bedford, MA DMA','Providence - Warwick - Pawtucket, RI NECMA'),
('RHODE ISLAND','RI','KENT','44','Providence, RI - New Bedford, MA DMA','Providence - Warwick - Pawtucket, RI NECMA'),
('RHODE ISLAND','RI','NEWPORT','44','Providence, RI - New Bedford, MA DMA','Not Assigned to Metro Area (NAM)'),
('RHODE ISLAND','RI','PROVIDENCE','44','Providence, RI - New Bedford, MA DMA','Providence - Warwick - Pawtucket, RI NECMA'),
('RHODE ISLAND','RI','WASHINGTON','44','Providence, RI - New Bedford, MA DMA','Providence - Warwick - Pawtucket, RI NECMA'),
('SOUTH CAROLINA','SC','ABBEVILLE','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','AIKEN','45','Augusta, GA - SC DMA','Augusta - Aiken, GA - SC MSA'),
('SOUTH CAROLINA','SC','ALLENDALE','45','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','ANDERSON','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Greenville - Spartanburg - Anderson, SC MSA'),
('SOUTH CAROLINA','SC','BAMBERG','45','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','BARNWELL','45','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','BEAUFORT','45','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','BERKELEY','45','Charleston, SC DMA','Charleston - North Charleston, SC MSA'),
('SOUTH CAROLINA','SC','CALHOUN','45','Columbia, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','CHARLESTON','45','Charleston, SC DMA','Charleston - North Charleston, SC MSA'),
('SOUTH CAROLINA','SC','CHEROKEE','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Greenville - Spartanburg - Anderson, SC MSA'),
('SOUTH CAROLINA','SC','CHESTER','45','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','CHESTERFIELD','45','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','CLARENDON','45','Columbia, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','COLLETON','45','Charleston, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','DARLINGTON','45','Florence - Myrtle Beach, SC - NC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','DILLON','45','Florence - Myrtle Beach, SC - NC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','DORCHESTER','45','Charleston, SC DMA','Charleston - North Charleston, SC MSA'),
('SOUTH CAROLINA','SC','EDGEFIELD','45','Augusta, GA - SC DMA','Augusta - Aiken, GA - SC MSA'),
('SOUTH CAROLINA','SC','FAIRFIELD','45','Columbia, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','FLORENCE','45','Florence - Myrtle Beach, SC - NC DMA','Florence, SC MSA'),
('SOUTH CAROLINA','SC','GEORGETOWN','45','Charleston, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','GREENVILLE','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Greenville - Spartanburg - Anderson, SC MSA'),
('SOUTH CAROLINA','SC','GREENWOOD','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','HAMPTON','45','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','HORRY','45','Florence - Myrtle Beach, SC - NC DMA','Myrtle Beach, SC MSA'),
('SOUTH CAROLINA','SC','JASPER','45','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','KERSHAW','45','Columbia, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','LANCASTER','45','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','LAURENS','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','LEE','45','Columbia, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','LEXINGTON','45','Columbia, SC DMA','Columbia, SC MSA'),
('SOUTH CAROLINA','SC','MCCORMICK','45','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','MARION','45','Florence - Myrtle Beach, SC - NC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','MARLBORO','45','Florence - Myrtle Beach, SC - NC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','NEWBERRY','45','Columbia, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','OCONEE','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','ORANGEBURG','45','Columbia, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','PICKENS','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Greenville - Spartanburg - Anderson, SC MSA'),
('SOUTH CAROLINA','SC','RICHLAND','45','Columbia, SC DMA','Columbia, SC MSA'),
('SOUTH CAROLINA','SC','SALUDA','45','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','SPARTANBURG','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Greenville - Spartanburg - Anderson, SC MSA'),
('SOUTH CAROLINA','SC','SUMTER','45','Columbia, SC DMA','Sumter, SC MSA'),
('SOUTH CAROLINA','SC','UNION','45','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','WILLIAMSBURG','45','Charleston, SC DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH CAROLINA','SC','YORK','45','Charlotte, NC - SC DMA','Charlotte - Gastonia - Rock Hill, NC - SC MSA'),
('SOUTH DAKOTA','SD','AURORA','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','BEADLE','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','BENNETT','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','BON HOMME','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','BROOKINGS','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','BROWN','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','BRULE','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','BUFFALO','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','BUTTE','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','CAMPBELL','46','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','CHARLES MIX','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','CLARK','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','CLAY','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','CODINGTON','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','CORSON','46','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','CUSTER','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','DAVISON','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','DAY','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','DEUEL','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','DEWEY','46','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','DOUGLAS','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','EDMUNDS','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','FALL RIVER','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','FAULK','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','GRANT','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','GREGORY','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','HAAKON','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','HAMLIN','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','HAND','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','HANSON','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','HARDING','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','HUGHES','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','HUTCHINSON','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','HYDE','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','JACKSON','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','JERAULD','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','JONES','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','KINGSBURY','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','LAKE','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','LAWRENCE','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','LINCOLN','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Sioux Falls, SD MSA'),
('SOUTH DAKOTA','SD','LYMAN','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','MCCOOK','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','MCPHERSON','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','MARSHALL','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','MEADE','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','MELLETTE','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','MINER','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','MINNEHAHA','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Sioux Falls, SD MSA'),
('SOUTH DAKOTA','SD','MOODY','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','PENNINGTON','46','Rapid City, SD - MT - NE - WY DMA','Rapid City, SD MSA'),
('SOUTH DAKOTA','SD','PERKINS','46','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','POTTER','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','ROBERTS','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','SANBORN','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','SHANNON','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','SPINK','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','STANLEY','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','SULLY','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','TODD','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','TRIPP','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','TURNER','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','UNION','46','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','WALWORTH','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','YANKTON','46','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('SOUTH DAKOTA','SD','ZIEBACH','46','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('STATE','STATE_AB','COUNTY','','TVDMA','Metropolitan_Statistical_Areas'),
('TENNESSEE','TN','ANDERSON','47','Knoxville, TN - KY DMA','Knoxville, TN MSA'),
('TENNESSEE','TN','BEDFORD','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','BENTON','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','BLEDSOE','47','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','BLOUNT','47','Knoxville, TN - KY DMA','Knoxville, TN MSA'),
('TENNESSEE','TN','BRADLEY','47','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','CAMPBELL','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','CANNON','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','CARROLL','47','Jackson, TN DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','CARTER','47','Tri - Cities, TN - VA - KY DMA','Johnson City - Kingsport - Bristol, TN - VA MSA'),
('TENNESSEE','TN','CHEATHAM','47','Nashville, TN - KY DMA','Nashville, TN MSA'),
('TENNESSEE','TN','CHESTER','47','Memphis, TN - AR- MS - MO DMA','Jackson, TN MSA'),
('TENNESSEE','TN','CLAIBORNE','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','CLAY','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','COCKE','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','COFFEE','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','CROCKETT','47','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','CUMBERLAND','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','DAVIDSON','47','Nashville, TN - KY DMA','Nashville, TN MSA'),
('TENNESSEE','TN','DECATUR','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','DE KALB','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','DICKSON','47','Nashville, TN - KY DMA','Nashville, TN MSA'),
('TENNESSEE','TN','DYER','47','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','FAYETTE','47','Memphis, TN - AR- MS - MO DMA','Memphis, TN - AR - MS MSA'),
('TENNESSEE','TN','FENTRESS','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','FRANKLIN','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','GIBSON','47','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','GILES','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','GRAINGER','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','GREENE','47','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','GRUNDY','47','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HAMBLEN','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HAMILTON','47','Chattanooga, TN - GA - NC DMA','Chattanooga, TN - GA MSA'),
('TENNESSEE','TN','HANCOCK','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HARDEMAN','47','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HARDIN','47','Jackson, TN DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HAWKINS','47','Tri - Cities, TN - VA - KY DMA','Johnson City - Kingsport - Bristol, TN - VA MSA'),
('TENNESSEE','TN','HAYWOOD','47','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HENDERSON','47','Jackson, TN DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HENRY','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HICKMAN','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HOUSTON','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','HUMPHREYS','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','JACKSON','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','JEFFERSON','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','JOHNSON','47','Tri - Cities, TN - VA - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','KNOX','47','Knoxville, TN - KY DMA','Knoxville, TN MSA'),
('TENNESSEE','TN','LAKE','47','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','LAUDERDALE','47','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','LAWRENCE','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','LEWIS','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','LINCOLN','47','Huntsville - Decatur - Florence, AL - TN DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','LOUDON','47','Knoxville, TN - KY DMA','Knoxville, TN MSA'),
('TENNESSEE','TN','MCMINN','47','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','MCNAIRY','47','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','MACON','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','MADISON','47','Jackson, TN DMA','Jackson, TN MSA'),
('TENNESSEE','TN','MARION','47','Chattanooga, TN - GA - NC DMA','Chattanooga, TN - GA MSA'),
('TENNESSEE','TN','MARSHALL','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','MAURY','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','MEIGS','47','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','MONROE','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','MONTGOMERY','47','Nashville, TN - KY DMA','Clarksville - Hopkinsville, TN - KY MSA'),
('TENNESSEE','TN','MOORE','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','MORGAN','47','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','OBION','47','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','OVERTON','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('TENNESSEE','TN','PERRY','47','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)');
