INSERT INTO dma_counties (state, state_abbr, county, state_fips, dma_name, msa) VALUES
('GEORGIA','GA','PUTNAM','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','QUITMAN','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','RABUN','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','RANDOLPH','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','RICHMOND','13','Augusta, GA - SC DMA','Augusta - Aiken, GA - SC MSA'),
('GEORGIA','GA','ROCKDALE','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','SCHLEY','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','SCREVEN','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','SEMINOLE','13','Dothan, AL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','SPALDING','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','STEPHENS','13','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','STEWART','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','SUMTER','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TALBOT','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TALIAFERRO','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TATTNALL','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TAYLOR','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TELFAIR','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TERRELL','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','THOMAS','13','Tallahassee - Thomasville, FL - GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TIFT','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TOOMBS','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TOWNS','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TREUTLEN','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TROUP','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TURNER','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','TWIGGS','13','Macon, GA DMA','Macon, GA MSA'),
('GEORGIA','GA','UNION','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','UPSON','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WALKER','13','Chattanooga, TN - GA - NC DMA','Chattanooga, TN - GA MSA'),
('GEORGIA','GA','WALTON','13','Atlanta, GA - AL - NC DMA','Atlanta, GA MSA'),
('GEORGIA','GA','WARE','13','Jacksonville, FL - Brunswick, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WARREN','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WASHINGTON','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WAYNE','13','Savannah, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WEBSTER','13','Columbus, GA - AL DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WHEELER','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WHITE','13','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WHITFIELD','13','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WILCOX','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WILKES','13','Augusta, GA - SC DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WILKINSON','13','Macon, GA DMA','Not Assigned to Metro Area (NAM)'),
('GEORGIA','GA','WORTH','13','Albany, GA DMA','Not Assigned to Metro Area (NAM)'),
('HAWAII','HI','HAWAII','15','Honolulu, HI DMA','Not Assigned to Metro Area (NAM)'),
('HAWAII','HI','HONOLULU','15','Honolulu, HI DMA','Honolulu, HI MSA'),
('HAWAII','HI','KAUAI','15','Honolulu, HI DMA','Not Assigned to Metro Area (NAM)'),
('HAWAII','HI','MAUI','15','Honolulu, HI DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','ADA','16','Boise, ID - OR DMA','Boise City, ID MSA'),
('IDAHO','ID','ADAMS','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BANNOCK','16','Idaho Falls - Pocatello, ID - WY DMA','Pocatello, ID MSA'),
('IDAHO','ID','BEAR LAKE','16','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BENEWAH','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BINGHAM','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BLAINE','16','Twin Falls, ID DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BOISE','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BONNER','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BONNEVILLE','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BOUNDARY','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','BUTTE','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','CAMAS','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','CANYON','16','Boise, ID - OR DMA','Boise City, ID MSA'),
('IDAHO','ID','CARIBOU','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','CASSIA','16','Twin Falls, ID DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','CLARK','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','CLEARWATER','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','CUSTER','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','ELMORE','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','FRANKLIN','16','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','FREMONT','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','GEM','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','GOODING','16','Twin Falls, ID DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','IDAHO','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','JEFFERSON','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','JEROME','16','Twin Falls, ID DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','KOOTENAI','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','LATAH','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','LEMHI','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','LEWIS','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','LINCOLN','16','Twin Falls, ID DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','MADISON','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','MINIDOKA','16','Twin Falls, ID DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','NEZ PERCE','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','ONEIDA','16','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','OWYHEE','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','PAYETTE','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','POWER','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','SHOSHONE','16','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','TETON','16','Idaho Falls - Pocatello, ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','TWIN FALLS','16','Twin Falls, ID DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','VALLEY','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('IDAHO','ID','WASHINGTON','16','Boise, ID - OR DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','ADAMS','17','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','ALEXANDER','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','BOND','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','BOONE','17','Rockford, IL DMA','Rockford, IL MSA'),
('ILLINOIS','IL','BROWN','17','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','BUREAU','17','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','CALHOUN','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','CARROLL','17','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','CASS','17','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','CHAMPAIGN','17','Champaign - Springfield - Decatur, IL DMA','Champaign - Urbana, IL MSA'),
('ILLINOIS','IL','CHRISTIAN','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','CLARK','17','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','CLAY','17','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','CLINTON','17','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('ILLINOIS','IL','COLES','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','COOK','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','CRAWFORD','17','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','CUMBERLAND','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','DE KALB','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','DE WITT','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','DOUGLAS','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','DU PAGE','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','EDGAR','17','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','EDWARDS','17','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','EFFINGHAM','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','FAYETTE','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','FORD','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','FRANKLIN','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','FULTON','17','Peoria - Bloomington, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','GALLATIN','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','GREENE','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','GRUNDY','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','HAMILTON','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','HANCOCK','17','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','HARDIN','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','HENDERSON','17','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','HENRY','17','Davenport - Rock Island - Moline, IA - IL DMA','Davenport - Moline - Rock Island, IA - IL MSA'),
('ILLINOIS','IL','IROQUOIS','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','JACKSON','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','JASPER','17','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','JEFFERSON','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','JERSEY','17','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('ILLINOIS','IL','JO DAVIESS','17','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','JOHNSON','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','KANE','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','KANKAKEE','17','Chicago, IL - IN DMA','Kankakee, IL PMSA'),
('ILLINOIS','IL','KENDALL','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','KNOX','17','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','LAKE','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','LA SALLE','17','Chicago, IL - IN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','LAWRENCE','17','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','LEE','17','Rockford, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','LIVINGSTON','17','Peoria - Bloomington, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','LOGAN','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MCDONOUGH','17','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MCHENRY','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','MCLEAN','17','Peoria - Bloomington, IL DMA','Bloomington - Normal, IL MSA'),
('ILLINOIS','IL','MACON','17','Champaign - Springfield - Decatur, IL DMA','Decatur, IL MSA'),
('ILLINOIS','IL','MACOUPIN','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MADISON','17','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('ILLINOIS','IL','MARION','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MARSHALL','17','Peoria - Bloomington, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MASON','17','Peoria - Bloomington, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MASSAC','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MENARD','17','Champaign - Springfield - Decatur, IL DMA','Springfield, IL MSA'),
('ILLINOIS','IL','MERCER','17','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MONROE','17','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('ILLINOIS','IL','MONTGOMERY','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MORGAN','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','MOULTRIE','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','OGLE','17','Rockford, IL DMA','Rockford, IL MSA'),
('ILLINOIS','IL','PEORIA','17','Peoria - Bloomington, IL DMA','Peoria - Pekin, IL MSA'),
('ILLINOIS','IL','PERRY','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','PIATT','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','PIKE','17','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','POPE','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','PULASKI','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','PUTNAM','17','Peoria - Bloomington, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','RANDOLPH','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','RICHLAND','17','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','ROCK ISLAND','17','Davenport - Rock Island - Moline, IA - IL DMA','Davenport - Moline - Rock Island, IA - IL MSA'),
('ILLINOIS','IL','ST CLAIR','17','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('ILLINOIS','IL','SALINE','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','SANGAMON','17','Champaign - Springfield - Decatur, IL DMA','Springfield, IL MSA'),
('ILLINOIS','IL','SCHUYLER','17','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','SCOTT','17','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','SHELBY','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','STARK','17','Peoria - Bloomington, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','STEPHENSON','17','Rockford, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','TAZEWELL','17','Peoria - Bloomington, IL DMA','Peoria - Pekin, IL MSA'),
('ILLINOIS','IL','UNION','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','VERMILION','17','Champaign - Springfield - Decatur, IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','WABASH','17','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','WARREN','17','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','WASHINGTON','17','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','WAYNE','17','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','WHITE','17','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','WHITESIDE','17','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','WILL','17','Chicago, IL - IN DMA','Chicago, IL PMSA'),
('ILLINOIS','IL','WILLIAMSON','17','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('ILLINOIS','IL','WINNEBAGO','17','Rockford, IL DMA','Rockford, IL MSA'),
('ILLINOIS','IL','WOODFORD','17','Peoria - Bloomington, IL DMA','Peoria - Pekin, IL MSA'),
('INDIANA','IN','ADAMS','18','Ft. Wayne, IN - OH DMA','Fort Wayne, IN MSA'),
('INDIANA','IN','ALLEN','18','Ft. Wayne, IN - OH DMA','Fort Wayne, IN MSA'),
('INDIANA','IN','BARTHOLOMEW','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','BENTON','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','BLACKFORD','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','BOONE','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','BROWN','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','CARROLL','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','CASS','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','CLARK','18','Louisville, KY - IN DMA','Louisville, KY - IN MSA'),
('INDIANA','IN','CLAY','18','Terre Haute, IN - IL DMA','Terre Haute, IN MSA'),
('INDIANA','IN','CLINTON','18','Indianapolis, IN DMA','Lafayette, IN MSA'),
('INDIANA','IN','CRAWFORD','18','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','DAVIESS','18','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','DEARBORN','18','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('INDIANA','IN','DECATUR','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','DE KALB','18','Ft. Wayne, IN - OH DMA','Fort Wayne, IN MSA'),
('INDIANA','IN','DELAWARE','18','Indianapolis, IN DMA','Muncie, IN MSA'),
('INDIANA','IN','DUBOIS','18','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','ELKHART','18','South Bend - Elkhart, IN - MI DMA','Elkhart - Goshen, IN MSA'),
('INDIANA','IN','FAYETTE','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','FLOYD','18','Louisville, KY - IN DMA','Louisville, KY - IN MSA'),
('INDIANA','IN','FOUNTAIN','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','FRANKLIN','18','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','FULTON','18','South Bend - Elkhart, IN - MI DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','GIBSON','18','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','GRANT','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','GREENE','18','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','HAMILTON','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','HANCOCK','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','HARRISON','18','Louisville, KY - IN DMA','Louisville, KY - IN MSA'),
('INDIANA','IN','HENDRICKS','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','HENRY','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','HOWARD','18','Indianapolis, IN DMA','Kokomo, IN MSA'),
('INDIANA','IN','HUNTINGTON','18','Ft. Wayne, IN - OH DMA','Fort Wayne, IN MSA'),
('INDIANA','IN','JACKSON','18','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','JASPER','18','Chicago, IL - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','JAY','18','Ft. Wayne, IN - OH DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','JEFFERSON','18','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','JENNINGS','18','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','JOHNSON','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','KNOX','18','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','KOSCIUSKO','18','South Bend - Elkhart, IN - MI DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','LAGRANGE','18','South Bend - Elkhart, IN - MI DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','LAKE','18','Chicago, IL - IN DMA','Gary, IN PMSA'),
('INDIANA','IN','LA PORTE','18','Chicago, IL - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','LAWRENCE','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','MADISON','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','MARION','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','MARSHALL','18','South Bend - Elkhart, IN - MI DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','MARTIN','18','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','MIAMI','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','MONROE','18','Indianapolis, IN DMA','Bloomington, IN MSA'),
('INDIANA','IN','MONTGOMERY','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','MORGAN','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','NEWTON','18','Chicago, IL - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','NOBLE','18','Ft. Wayne, IN - OH DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','OHIO','18','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('INDIANA','IN','ORANGE','18','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','OWEN','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','PARKE','18','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','PERRY','18','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','PIKE','18','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','PORTER','18','Chicago, IL - IN DMA','Gary, IN PMSA'),
('INDIANA','IN','POSEY','18','Evansville, IN - IL - KY DMA','Evansville - Henderson, IN - KY MSA'),
('INDIANA','IN','PULASKI','18','South Bend - Elkhart, IN - MI DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','PUTNAM','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','RANDOLPH','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','RIPLEY','18','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','RUSH','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','ST JOSEPH','18','South Bend - Elkhart, IN - MI DMA','South Bend, IN MSA'),
('INDIANA','IN','SCOTT','18','Louisville, KY - IN DMA','Louisville, KY - IN MSA'),
('INDIANA','IN','SHELBY','18','Indianapolis, IN DMA','Indianapolis, IN MSA'),
('INDIANA','IN','SPENCER','18','Evansville, IN - IL - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','STARKE','18','South Bend - Elkhart, IN - MI DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','STEUBEN','18','Ft. Wayne, IN - OH DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','SULLIVAN','18','Terre Haute, IN - IL DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','SWITZERLAND','18','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','TIPPECANOE','18','Lafayette, IN DMA','Lafayette, IN MSA'),
('INDIANA','IN','TIPTON','18','Indianapolis, IN DMA','Kokomo, IN MSA'),
('INDIANA','IN','UNION','18','Cincinnati, OH -IN - KY DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','VANDERBURGH','18','Evansville, IN - IL - KY DMA','Evansville - Henderson, IN - KY MSA'),
('INDIANA','IN','VERMILLION','18','Terre Haute, IN - IL DMA','Terre Haute, IN MSA'),
('INDIANA','IN','VIGO','18','Terre Haute, IN - IL DMA','Terre Haute, IN MSA'),
('INDIANA','IN','WABASH','18','Ft. Wayne, IN - OH DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','WARREN','18','Lafayette, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','WARRICK','18','Evansville, IN - IL - KY DMA','Evansville - Henderson, IN - KY MSA'),
('INDIANA','IN','WASHINGTON','18','Louisville, KY - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','WAYNE','18','Dayton, OH - IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','WELLS','18','Ft. Wayne, IN - OH DMA','Fort Wayne, IN MSA'),
('INDIANA','IN','WHITE','18','Indianapolis, IN DMA','Not Assigned to Metro Area (NAM)'),
('INDIANA','IN','WHITLEY','18','Ft. Wayne, IN - OH DMA','Fort Wayne, IN MSA'),
('IOWA','IA','ADAIR','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','ADAMS','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','ALLAMAKEE','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','APPANOOSE','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','AUDUBON','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','BENTON','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','BLACK HAWK','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Waterloo - Cedar Falls, IA MSA'),
('IOWA','IA','BOONE','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','BREMER','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','BUCHANAN','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','BUENA VISTA','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','BUTLER','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CALHOUN','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CARROLL','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CASS','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CEDAR','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CERRO GORDO','19','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CHEROKEE','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CHICKASAW','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CLARKE','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CLAY','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CLAYTON','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CLINTON','19','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','CRAWFORD','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','DALLAS','19','Des Moines - Ames, IA - MO DMA','Des Moines, IA MSA'),
('IOWA','IA','DAVIS','19','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','DECATUR','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','DELAWARE','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','DES MOINES','19','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','DICKINSON','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','DUBUQUE','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Dubuque, IA MSA'),
('IOWA','IA','EMMET','19','Mankato, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','FAYETTE','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','FLOYD','19','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','FRANKLIN','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','FREMONT','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','GREENE','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','GRUNDY','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','GUTHRIE','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','HAMILTON','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','HANCOCK','19','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','HARDIN','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','HARRISON','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','HENRY','19','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','HOWARD','19','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','HUMBOLDT','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','IDA','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','IOWA','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','JACKSON','19','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','JASPER','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','JEFFERSON','19','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','JOHNSON','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Iowa City, IA MSA'),
('IOWA','IA','JONES','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','KEOKUK','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','KOSSUTH','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','LEE','19','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','LINN','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Cedar Rapids, IA MSA'),
('IOWA','IA','LOUISA','19','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','LUCAS','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','LYON','19','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MADISON','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MAHASKA','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MARION','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MARSHALL','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MILLS','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MITCHELL','19','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MONONA','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MONROE','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MONTGOMERY','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','MUSCATINE','19','Davenport - Rock Island - Moline, IA - IL DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','O BRIEN','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','OSCEOLA','19','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','PAGE','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','PALO ALTO','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','PLYMOUTH','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','POCAHONTAS','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','POLK','19','Des Moines - Ames, IA - MO DMA','Des Moines, IA MSA'),
('IOWA','IA','POTTAWATTAMIE','19','Omaha, NE - IA - MO DMA','Omaha, NE - IA MSA'),
('IOWA','IA','POWESHIEK','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','RINGGOLD','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','SAC','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','SCOTT','19','Davenport - Rock Island - Moline, IA - IL DMA','Davenport - Moline - Rock Island, IA - IL MSA'),
('IOWA','IA','SHELBY','19','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','SIOUX','19','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','STORY','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','TAMA','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','TAYLOR','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','UNION','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','VAN BUREN','19','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','WAPELLO','19','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','WARREN','19','Des Moines - Ames, IA - MO DMA','Des Moines, IA MSA'),
('IOWA','IA','WASHINGTON','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','WAYNE','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','WEBSTER','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','WINNEBAGO','19','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','WINNESHIEK','19','Cedar Rapids - Waterloo&Dubuque, IA - WI DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','WOODBURY','19','Sioux City, IA - NE - SD DMA','Sioux City, IA - NE MSA'),
('IOWA','IA','WORTH','19','Rochester - Mason City - Austin, MN - IA DMA','Not Assigned to Metro Area (NAM)'),
('IOWA','IA','WRIGHT','19','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','ALLEN','20','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','ANDERSON','20','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','ATCHISON','20','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','BARBER','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','BARTON','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','BOURBON','20','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','BROWN','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','BUTLER','20','Wichita - Hutchinson Plus, KS - NE DMA','Wichita, KS MSA'),
('KANSAS','KS','CHASE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','CHAUTAUQUA','20','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','CHEROKEE','20','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','CHEYENNE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','CLARK','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','CLAY','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','CLOUD','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','COFFEY','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','COMANCHE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','COWLEY','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','CRAWFORD','20','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','DECATUR','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','DICKINSON','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','DONIPHAN','20','St. Joseph, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','DOUGLAS','20','Kansas City, MO - KS DMA','Lawrence, KS MSA'),
('KANSAS','KS','EDWARDS','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','ELK','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','ELLIS','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','ELLSWORTH','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','FINNEY','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','FORD','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','FRANKLIN','20','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','GEARY','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','GOVE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','GRAHAM','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','GRANT','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','GRAY','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','GREELEY','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','GREENWOOD','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','HAMILTON','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','HARPER','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','HARVEY','20','Wichita - Hutchinson Plus, KS - NE DMA','Wichita, KS MSA'),
('KANSAS','KS','HASKELL','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','HODGEMAN','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','JACKSON','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','JEFFERSON','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','JEWELL','20','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','JOHNSON','20','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('KANSAS','KS','KEARNY','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','KINGMAN','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','KIOWA','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','LABETTE','20','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','LANE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','LEAVENWORTH','20','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('KANSAS','KS','LINCOLN','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','LINN','20','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','LOGAN','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','LYON','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','MCPHERSON','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','MARION','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','MARSHALL','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','MEADE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','MIAMI','20','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('KANSAS','KS','MITCHELL','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','MONTGOMERY','20','Tulsa, OK - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','MORRIS','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','MORTON','20','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','NEMAHA','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','NEOSHO','20','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','NESS','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','NORTON','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','OSAGE','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','OSBORNE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','OTTAWA','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','PAWNEE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','PHILLIPS','20','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','POTTAWATOMIE','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','PRATT','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','RAWLINS','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','RENO','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','REPUBLIC','20','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','RICE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','RILEY','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','ROOKS','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','RUSH','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','RUSSELL','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','SALINE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','SCOTT','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','SEDGWICK','20','Wichita - Hutchinson Plus, KS - NE DMA','Wichita, KS MSA'),
('KANSAS','KS','SEWARD','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','SHAWNEE','20','Topeka, KS DMA','Topeka, KS MSA'),
('KANSAS','KS','SHERIDAN','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','SHERMAN','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','SMITH','20','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','STAFFORD','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','STANTON','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','STEVENS','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','SUMNER','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','THOMAS','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','TREGO','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','WABAUNSEE','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','WALLACE','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','WASHINGTON','20','Topeka, KS DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','WICHITA','20','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','WILSON','20','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','WOODSON','20','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('KANSAS','KS','WYANDOTTE','20','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('KENTUCKY','KY','ADAIR','21','Bowling Green, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','ALLEN','21','Nashville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','ANDERSON','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','BALLARD','21','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','BARREN','21','Bowling Green, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','BATH','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','BELL','21','Knoxville, TN - KY DMA','Not Assigned to Metro Area (NAM)'),
('KENTUCKY','KY','BOONE','21','Cincinnati, OH -IN - KY DMA','Cincinnati, OH - KY - IN PMSA'),
('KENTUCKY','KY','BOURBON','21','Lexington, KY DMA','Lexington, KY MSA'),
('KENTUCKY','KY','BOYD','21','Charleston - Huntington, WV - KY - OH DMA','Huntington - Ashland, WV - KY - OH MSA'),
('KENTUCKY','KY','BOYLE','21','Lexington, KY DMA','Not Assigned to Metro Area (NAM)');
