INSERT INTO dma_counties (state, state_abbr, county, state_fips, dma_name, msa) VALUES
('MISSOURI','MO','CHRISTIAN','29','Springfield, MO - AR DMA','Springfield, MO MSA'),
('MISSOURI','MO','CLARK','29','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CLAY','29','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('MISSOURI','MO','CLINTON','29','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('MISSOURI','MO','COLE','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','COOPER','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','CRAWFORD','29','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','DADE','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','DALLAS','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','DAVIESS','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','DE KALB','29','St. Joseph, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','DENT','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','DOUGLAS','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','DUNKLIN','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','FRANKLIN','29','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('MISSOURI','MO','GASCONADE','29','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','GENTRY','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','GREENE','29','Springfield, MO - AR DMA','Springfield, MO MSA'),
('MISSOURI','MO','GRUNDY','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','HARRISON','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','HENRY','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','HICKORY','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','HOLT','29','St. Joseph, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','HOWARD','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','HOWELL','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','IRON','29','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','JACKSON','29','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('MISSOURI','MO','JASPER','29','Joplin - Pittsburg, MO - KS - OK DMA','Joplin, MO MSA'),
('MISSOURI','MO','JEFFERSON','29','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('MISSOURI','MO','JOHNSON','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','KNOX','29','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','LACLEDE','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','LAFAYETTE','29','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('MISSOURI','MO','LAWRENCE','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','LEWIS','29','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','LINCOLN','29','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('MISSOURI','MO','LINN','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','LIVINGSTON','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MCDONALD','29','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MACON','29','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MADISON','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MARIES','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MARION','29','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MERCER','29','Des Moines - Ames, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MILLER','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MISSISSIPPI','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MONITEAU','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MONROE','29','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MONTGOMERY','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','MORGAN','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','NEW MADRID','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','NEWTON','29','Joplin - Pittsburg, MO - KS - OK DMA','Joplin, MO MSA'),
('MISSOURI','MO','NODAWAY','29','St. Joseph, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','OREGON','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','OSAGE','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','OZARK','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','PEMISCOT','29','Memphis, TN - AR- MS - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','PERRY','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','PETTIS','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','PHELPS','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','PIKE','29','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','PLATTE','29','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('MISSOURI','MO','POLK','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','PULASKI','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','PUTNAM','29','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','RALLS','29','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','RANDOLPH','29','Columbia - Jefferson City, MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','RAY','29','Kansas City, MO - KS DMA','Kansas City, MO - KS MSA'),
('MISSOURI','MO','REYNOLDS','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','RIPLEY','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','ST CHARLES','29','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('MISSOURI','MO','ST CLAIR','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','STE GENEVIEVE','29','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','ST FRANCOIS','29','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','ST LOUIS','29','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('MISSOURI','MO','SALINE','29','Kansas City, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','SCHUYLER','29','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','SCOTLAND','29','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','SCOTT','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','SHANNON','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','SHELBY','29','Quincy - Hannibal - Keokuk, MO - IL - IA DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','STODDARD','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','STONE','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','SULLIVAN','29','Ottumwa - Kirksville, IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','TANEY','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','TEXAS','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','VERNON','29','Joplin - Pittsburg, MO - KS - OK DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','WARREN','29','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('MISSOURI','MO','WASHINGTON','29','St. Louis, MO - IL DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','WAYNE','29','Paducah - Cape Giradeau - Harrisburg, KY - IL - MO - TN DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','WEBSTER','29','Springfield, MO - AR DMA','Springfield, MO MSA'),
('MISSOURI','MO','WORTH','29','St. Joseph, MO - KS DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','WRIGHT','29','Springfield, MO - AR DMA','Not Assigned to Metro Area (NAM)'),
('MISSOURI','MO','ST LOUIS CITY','29','St. Louis, MO - IL DMA','St. Louis, MO - IL MSA'),
('MONTANA','MT','BEAVERHEAD','30','Butte - Bozeman, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','BIG HORN','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','BLAINE','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','BROADWATER','30','Butte - Bozeman, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','CARBON','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','CARTER','30','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','CASCADE','30','Great Falls, MT DMA','Great Falls, MT MSA'),
('MONTANA','MT','CHOUTEAU','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','CUSTER','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','DANIELS','30','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','DAWSON','30','Glendive, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','DEER LODGE','30','Butte - Bozeman, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','FALLON','30','Glendive, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','FERGUS','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','FLATHEAD','30','Missoula, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','GALLATIN','30','Butte - Bozeman, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','GARFIELD','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','GLACIER','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','GOLDEN VALLEY','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','GRANITE','30','Missoula, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','HILL','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','JEFFERSON','30','Butte - Bozeman, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','JUDITH BASIN','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','LAKE','30','Missoula, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','LEWIS AND CLARK','30','Helena, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','LIBERTY','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','LINCOLN','30','Spokane, WA - ID - MT - OR DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','MCCONE','30','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','MADISON','30','Butte - Bozeman, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','MEAGHER','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','MINERAL','30','Missoula, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','MISSOULA','30','Missoula, MT DMA','Missoula, MT MSA'),
('MONTANA','MT','MUSSELSHELL','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','PARK','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','PETROLEUM','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','PHILLIPS','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','PONDERA','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','POWDER RIVER','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','POWELL','30','Butte - Bozeman, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','PRAIRIE','30','Glendive, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','RAVALLI','30','Missoula, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','RICHLAND','30','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','ROOSEVELT','30','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','ROSEBUD','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','SANDERS','30','Missoula, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','SHERIDAN','30','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','SILVER BOW','30','Butte - Bozeman, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','STILLWATER','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','SWEET GRASS','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','TETON','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','TOOLE','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','TREASURE','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','VALLEY','30','Great Falls, MT DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','WHEATLAND','30','Billings, MT - ID DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','WIBAUX','30','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('MONTANA','MT','YELLOWSTONE','30','Billings, MT - ID DMA','Billings, MT MSA'),
('NEBRASKA','NE','ADAMS','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','ANTELOPE','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','ARTHUR','31','North Platte, NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BANNER','31','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BLAINE','31','North Platte, NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BOONE','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BOX BUTTE','31','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BOYD','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BROWN','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BUFFALO','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BURT','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','BUTLER','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','CASS','31','Omaha, NE - IA - MO DMA','Omaha, NE - IA MSA'),
('NEBRASKA','NE','CEDAR','31','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','CHASE','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','CHERRY','31','Sioux Falls (Mitchell), SD - IA - MN - NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','CHEYENNE','31','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','CLAY','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','COLFAX','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','CUMING','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','CUSTER','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','DAKOTA','31','Sioux City, IA - NE - SD DMA','Sioux City, IA - NE MSA'),
('NEBRASKA','NE','DAWES','31','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','DAWSON','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','DEUEL','31','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','DIXON','31','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','DODGE','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','DOUGLAS','31','Omaha, NE - IA - MO DMA','Omaha, NE - IA MSA'),
('NEBRASKA','NE','DUNDY','31','Wichita - Hutchinson Plus, KS - NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','FILLMORE','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','FRANKLIN','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','FRONTIER','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','FURNAS','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','GAGE','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','GARDEN','31','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','GARFIELD','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','GOSPER','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','GRANT','31','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','GREELEY','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','HALL','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','HAMILTON','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','HARLAN','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','HAYES','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','HITCHCOCK','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','HOLT','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','HOOKER','31','North Platte, NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','HOWARD','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','JEFFERSON','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','JOHNSON','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','KEARNEY','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','KEITH','31','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','KEYA PAHA','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','KIMBALL','31','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','KNOX','31','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','LANCASTER','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Lincoln, NE MSA'),
('NEBRASKA','NE','LINCOLN','31','North Platte, NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','LOGAN','31','North Platte, NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','LOUP','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','MCPHERSON','31','North Platte, NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','MADISON','31','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','MERRICK','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','MORRILL','31','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','NANCE','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','NEMAHA','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','NUCKOLLS','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','OTOE','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','PAWNEE','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','PERKINS','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','PHELPS','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','PIERCE','31','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','PLATTE','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','POLK','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','RED WILLOW','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','RICHARDSON','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','ROCK','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','SALINE','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','SARPY','31','Omaha, NE - IA - MO DMA','Omaha, NE - IA MSA'),
('NEBRASKA','NE','SAUNDERS','31','Omaha, NE - IA - MO DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','SCOTTS BLUFF','31','Cheyenne - Scottsbluff - Sterling, WY - NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','SEWARD','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','SHERIDAN','31','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','SHERMAN','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','SIOUX','31','Rapid City, SD - MT - NE - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','STANTON','31','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','THAYER','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','THOMAS','31','North Platte, NE DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','THURSTON','31','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','VALLEY','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','WASHINGTON','31','Omaha, NE - IA - MO DMA','Omaha, NE - IA MSA'),
('NEBRASKA','NE','WAYNE','31','Sioux City, IA - NE - SD DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','WEBSTER','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','WHEELER','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEBRASKA','NE','YORK','31','Lincoln & Hastings - Kearney Plus, NE - KS DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','CHURCHILL','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','CLARK','32','Las Vegas, NV DMA','Las Vegas, NV - AZ MSA'),
('NEVADA','NV','DOUGLAS','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','ELKO','32','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','ESMERALDA','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','EUREKA','32','Denver, CO - NE - NV - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','HUMBOLDT','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','LANDER','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','LINCOLN','32','Las Vegas, NV DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','LYON','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','MINERAL','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','NYE','32','Las Vegas, NV DMA','Las Vegas, NV - AZ MSA'),
('NEVADA','NV','PERSHING','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','STOREY','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','WASHOE','32','Reno, NV - CA DMA','Reno, NV MSA'),
('NEVADA','NV','WHITE PINE','32','Salt Lake City, UT - ID - WY DMA','Not Assigned to Metro Area (NAM)'),
('NEVADA','NV','CARSON CITY','32','Reno, NV - CA DMA','Not Assigned to Metro Area (NAM)'),
('NEW HAMPSHIRE','NH','BELKNAP','33','Boston, MA - NH DMA','Not Assigned to Metro Area (NAM)'),
('NEW HAMPSHIRE','NH','CARROLL','33','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('NEW HAMPSHIRE','NH','CHESHIRE','33','Boston, MA - NH DMA','Not Assigned to Metro Area (NAM)'),
('NEW HAMPSHIRE','NH','COOS','33','Portland - Auburn, ME - NH - VT DMA','Not Assigned to Metro Area (NAM)'),
('NEW HAMPSHIRE','NH','GRAFTON','33','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW HAMPSHIRE','NH','HILLSBOROUGH','33','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('NEW HAMPSHIRE','NH','MERRIMACK','33','Boston, MA - NH DMA','Not Assigned to Metro Area (NAM)'),
('NEW HAMPSHIRE','NH','ROCKINGHAM','33','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('NEW HAMPSHIRE','NH','STRAFFORD','33','Boston, MA - NH DMA','Boston- Worcester- Lawrence- Lowell- Brockton, MA - NH NECMA'),
('NEW HAMPSHIRE','NH','SULLIVAN','33','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW JERSEY','NJ','ATLANTIC','34','Philadelphia, PA - DE - NJ DMA','Atlantic - Cape May, NJ PMSA'),
('NEW JERSEY','NJ','BERGEN','34','New York, NY - CT - NJ - PA DMA','Bergen - Passaic, NJ PMSA'),
('NEW JERSEY','NJ','BURLINGTON','34','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('NEW JERSEY','NJ','CAMDEN','34','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('NEW JERSEY','NJ','CAPE MAY','34','Philadelphia, PA - DE - NJ DMA','Atlantic - Cape May, NJ PMSA'),
('NEW JERSEY','NJ','CUMBERLAND','34','Philadelphia, PA - DE - NJ DMA','Vineland - Millville - Bridgeton, NJ PMSA'),
('NEW JERSEY','NJ','ESSEX','34','New York, NY - CT - NJ - PA DMA','Newark, NJ PMSA'),
('NEW JERSEY','NJ','GLOUCESTER','34','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('NEW JERSEY','NJ','HUDSON','34','New York, NY - CT - NJ - PA DMA','Jersey City, NJ PMSA'),
('NEW JERSEY','NJ','HUNTERDON','34','New York, NY - CT - NJ - PA DMA','Middlesex - Somerset - Hunterdon, NJ PMSA'),
('NEW JERSEY','NJ','MERCER','34','Philadelphia, PA - DE - NJ DMA','Trenton, NJ PMSA'),
('NEW JERSEY','NJ','MIDDLESEX','34','New York, NY - CT - NJ - PA DMA','Middlesex - Somerset - Hunterdon, NJ PMSA'),
('NEW JERSEY','NJ','MONMOUTH','34','New York, NY - CT - NJ - PA DMA','Monmouth - Ocean, NJ PMSA'),
('NEW JERSEY','NJ','MORRIS','34','New York, NY - CT - NJ - PA DMA','Newark, NJ PMSA'),
('NEW JERSEY','NJ','OCEAN','34','New York, NY - CT - NJ - PA DMA','Monmouth - Ocean, NJ PMSA'),
('NEW JERSEY','NJ','PASSAIC','34','New York, NY - CT - NJ - PA DMA','Bergen - Passaic, NJ PMSA'),
('NEW JERSEY','NJ','SALEM','34','Philadelphia, PA - DE - NJ DMA','Philadelphia, PA - NJ PMSA'),
('NEW JERSEY','NJ','SOMERSET','34','New York, NY - CT - NJ - PA DMA','Middlesex - Somerset - Hunterdon, NJ PMSA'),
('NEW JERSEY','NJ','SUSSEX','34','New York, NY - CT - NJ - PA DMA','Newark, NJ PMSA'),
('NEW JERSEY','NJ','UNION','34','New York, NY - CT - NJ - PA DMA','Newark, NJ PMSA'),
('NEW JERSEY','NJ','WARREN','34','New York, NY - CT - NJ - PA DMA','Newark, NJ PMSA'),
('NEW MEXICO','NM','BERNALILLO','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Albuquerque, NM MSA'),
('NEW MEXICO','NM','CATRON','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','CHAVES','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','CIBOLA','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','COLFAX','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','CURRY','35','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','DE BACA','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','DONA ANA','35','El Paso, TX - NM DMA','Las Cruces, NM MSA'),
('NEW MEXICO','NM','EDDY','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','GRANT','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','GUADALUPE','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','HARDING','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','HIDALGO','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','LEA','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','LINCOLN','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','LOS ALAMOS','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Santa Fe, NM MSA'),
('NEW MEXICO','NM','LUNA','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','MCKINLEY','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','MORA','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','OTERO','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','QUAY','35','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','RIO ARRIBA','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','ROOSEVELT','35','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','SANDOVAL','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Albuquerque, NM MSA'),
('NEW MEXICO','NM','SAN JUAN','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','SAN MIGUEL','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','SANTA FE','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Santa Fe, NM MSA'),
('NEW MEXICO','NM','SIERRA','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','SOCORRO','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','TAOS','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','TORRANCE','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','UNION','35','Amarillo, TX -NM - OK DMA','Not Assigned to Metro Area (NAM)'),
('NEW MEXICO','NM','VALENCIA','35','Albuquerque - Santa Fe, NM - AZ - CO DMA','Albuquerque, NM MSA'),
('NEW YORK','NY','ALBANY','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Albany - Schenectady - Troy, NY MSA'),
('NEW YORK','NY','ALLEGANY','36','Buffalo, NY - PA DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','BRONX','36','New York, NY - CT - NJ - PA DMA','New York, NY PMSA'),
('NEW YORK','NY','BROOME','36','Binghamton, NY DMA','Binghamton, NY MSA'),
('NEW YORK','NY','CATTARAUGUS','36','Buffalo, NY - PA DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','CAYUGA','36','Syracuse, NY DMA*','Syracuse, NY MSA'),
('NEW YORK','NY','CHAUTAUQUA','36','Buffalo, NY - PA DMA','Jamestown, NY MSA'),
('NEW YORK','NY','CHEMUNG','36','Elmira, NY - PA DMA','Elmira, NY MSA'),
('NEW YORK','NY','CHENANGO','36','Binghamton, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','CLINTON','36','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','COLUMBIA','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','CORTLAND','36','Syracuse, NY DMA*','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','DELAWARE','36','Binghamton, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','DUTCHESS','36','New York, NY - CT - NJ - PA DMA','Dutchess County, NY PMSA'),
('NEW YORK','NY','ERIE','36','Buffalo, NY - PA DMA','Buffalo - Niagara Falls, NY MSA'),
('NEW YORK','NY','ESSEX','36','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','FRANKLIN','36','Burlington, VT - Plattsburgh, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','FULTON','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','GENESEE','36','Buffalo, NY - PA DMA','Rochester, NY MSA'),
('NEW YORK','NY','GREENE','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','HAMILTON','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','HERKIMER','36','Utica, NY DMA*','Utica - Rome, NY MSA'),
('NEW YORK','NY','JEFFERSON','36','Watertown, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','KINGS','36','New York, NY - CT - NJ - PA DMA','New York, NY PMSA'),
('NEW YORK','NY','LEWIS','36','Watertown, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','LIVINGSTON','36','Rochester, NY DMA','Rochester, NY MSA'),
('NEW YORK','NY','MADISON','36','Syracuse, NY DMA*','Syracuse, NY MSA'),
('NEW YORK','NY','MONROE','36','Rochester, NY DMA','Rochester, NY MSA'),
('NEW YORK','NY','MONTGOMERY','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Albany - Schenectady - Troy, NY MSA'),
('NEW YORK','NY','NASSAU','36','New York, NY - CT - NJ - PA DMA','Nassau - Suffolk, NY PMSA'),
('NEW YORK','NY','NEW YORK','36','New York, NY - CT - NJ - PA DMA','New York, NY PMSA'),
('NEW YORK','NY','NIAGARA','36','Buffalo, NY - PA DMA','Buffalo - Niagara Falls, NY MSA'),
('NEW YORK','NY','ONEIDA','36','Utica, NY DMA*','Utica - Rome, NY MSA'),
('NEW YORK','NY','ONONDAGA','36','Syracuse, NY DMA*','Syracuse, NY MSA'),
('NEW YORK','NY','ONTARIO','36','Rochester, NY DMA','Rochester, NY MSA'),
('NEW YORK','NY','ORANGE','36','New York, NY - CT - NJ - PA DMA','Newburgh, NY - PA PMSA'),
('NEW YORK','NY','ORLEANS','36','Buffalo, NY - PA DMA','Rochester, NY MSA'),
('NEW YORK','NY','OSWEGO','36','Syracuse, NY DMA*','Syracuse, NY MSA'),
('NEW YORK','NY','OTSEGO','36','Utica, NY DMA*','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','PUTNAM','36','New York, NY - CT - NJ - PA DMA','New York, NY PMSA'),
('NEW YORK','NY','QUEENS','36','New York, NY - CT - NJ - PA DMA','New York, NY PMSA'),
('NEW YORK','NY','RENSSELAER','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Albany - Schenectady - Troy, NY MSA'),
('NEW YORK','NY','RICHMOND','36','New York, NY - CT - NJ - PA DMA','New York, NY PMSA'),
('NEW YORK','NY','ROCKLAND','36','New York, NY - CT - NJ - PA DMA','New York, NY PMSA'),
('NEW YORK','NY','ST LAWRENCE','36','Watertown, NY DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','SARATOGA','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Albany - Schenectady - Troy, NY MSA'),
('NEW YORK','NY','SCHENECTADY','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Albany - Schenectady - Troy, NY MSA'),
('NEW YORK','NY','SCHOHARIE','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Albany - Schenectady - Troy, NY MSA'),
('NEW YORK','NY','SCHUYLER','36','Elmira, NY - PA DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','SENECA','36','Syracuse, NY DMA*','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','STEUBEN','36','Elmira, NY - PA DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','SUFFOLK','36','New York, NY - CT - NJ - PA DMA','Nassau - Suffolk, NY PMSA'),
('NEW YORK','NY','SULLIVAN','36','New York, NY - CT - NJ - PA DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','TIOGA','36','Binghamton, NY DMA','Binghamton, NY MSA'),
('NEW YORK','NY','TOMPKINS','36','Syracuse, NY DMA*','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','ULSTER','36','New York, NY - CT - NJ - PA DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','WARREN','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Glens Falls, NY MSA'),
('NEW YORK','NY','WASHINGTON','36','Albany - Schenectady - Troy, NY - MA - VT DMA','Glens Falls, NY MSA'),
('NEW YORK','NY','WAYNE','36','Rochester, NY DMA','Rochester, NY MSA'),
('NEW YORK','NY','WESTCHESTER','36','New York, NY - CT - NJ - PA DMA','New York, NY PMSA'),
('NEW YORK','NY','WYOMING','36','Buffalo, NY - PA DMA','Not Assigned to Metro Area (NAM)'),
('NEW YORK','NY','YATES','36','Rochester, NY DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','ALAMANCE','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Greensboro - Winston-Salem - High Point, NC MSA'),
('NORTH CAROLINA','NC','ALEXANDER','37','Charlotte, NC - SC DMA','Hickory - Morganton - Lenoir, NC MSA'),
('NORTH CAROLINA','NC','ALLEGHANY','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','ANSON','37','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','ASHE','37','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','AVERY','37','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','BEAUFORT','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','BERTIE','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','BLADEN','37','Wilmington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','BRUNSWICK','37','Wilmington, NC DMA','Wilmington, NC MSA'),
('NORTH CAROLINA','NC','BUNCOMBE','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Asheville, NC MSA'),
('NORTH CAROLINA','NC','BURKE','37','Charlotte, NC - SC DMA','Hickory - Morganton - Lenoir, NC MSA'),
('NORTH CAROLINA','NC','CABARRUS','37','Charlotte, NC - SC DMA','Charlotte - Gastonia - Rock Hill, NC - SC MSA'),
('NORTH CAROLINA','NC','CALDWELL','37','Charlotte, NC - SC DMA','Hickory - Morganton - Lenoir, NC MSA'),
('NORTH CAROLINA','NC','CAMDEN','37','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','CARTERET','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','CASWELL','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','CATAWBA','37','Charlotte, NC - SC DMA','Hickory - Morganton - Lenoir, NC MSA'),
('NORTH CAROLINA','NC','CHATHAM','37','Raleigh - Durham, NC - VA DMA','Raleigh - Durham - Chapel Hill, NC MSA'),
('NORTH CAROLINA','NC','CHEROKEE','37','Chattanooga, TN - GA - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','CHOWAN','37','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','CLAY','37','Atlanta, GA - AL - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','CLEVELAND','37','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','COLUMBUS','37','Wilmington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','CRAVEN','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','CUMBERLAND','37','Raleigh - Durham, NC - VA DMA','Fayetteville, NC MSA'),
('NORTH CAROLINA','NC','CURRITUCK','37','Norfolk - Portsmouth - Newport News, VA - NC DMA','Norfolk - Virginia Beach - Newport News, VA - NC MSA'),
('NORTH CAROLINA','NC','DARE','37','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','DAVIDSON','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Greensboro - Winston-Salem - High Point, NC MSA'),
('NORTH CAROLINA','NC','DAVIE','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Greensboro - Winston-Salem - High Point, NC MSA'),
('NORTH CAROLINA','NC','DUPLIN','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','DURHAM','37','Raleigh - Durham, NC - VA DMA','Raleigh - Durham - Chapel Hill, NC MSA'),
('NORTH CAROLINA','NC','EDGECOMBE','37','Raleigh - Durham, NC - VA DMA','Rocky Mount, NC MSA'),
('NORTH CAROLINA','NC','FORSYTH','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Greensboro - Winston-Salem - High Point, NC MSA'),
('NORTH CAROLINA','NC','FRANKLIN','37','Raleigh - Durham, NC - VA DMA','Raleigh - Durham - Chapel Hill, NC MSA'),
('NORTH CAROLINA','NC','GASTON','37','Charlotte, NC - SC DMA','Charlotte - Gastonia - Rock Hill, NC - SC MSA'),
('NORTH CAROLINA','NC','GATES','37','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','GRAHAM','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','GRANVILLE','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','GREENE','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','GUILFORD','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Greensboro - Winston-Salem - High Point, NC MSA'),
('NORTH CAROLINA','NC','HALIFAX','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','HARNETT','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','HAYWOOD','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','HENDERSON','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','HERTFORD','37','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','HOKE','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','HYDE','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','IREDELL','37','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','JACKSON','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','JOHNSTON','37','Raleigh - Durham, NC - VA DMA','Raleigh - Durham - Chapel Hill, NC MSA'),
('NORTH CAROLINA','NC','JONES','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','LEE','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','LENOIR','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','LINCOLN','37','Charlotte, NC - SC DMA','Charlotte - Gastonia - Rock Hill, NC - SC MSA'),
('NORTH CAROLINA','NC','MCDOWELL','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','MACON','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','MADISON','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Asheville, NC MSA'),
('NORTH CAROLINA','NC','MARTIN','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','MECKLENBURG','37','Charlotte, NC - SC DMA','Charlotte - Gastonia - Rock Hill, NC - SC MSA'),
('NORTH CAROLINA','NC','MITCHELL','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','MONTGOMERY','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','MOORE','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','NASH','37','Raleigh - Durham, NC - VA DMA','Rocky Mount, NC MSA'),
('NORTH CAROLINA','NC','NEW HANOVER','37','Wilmington, NC DMA','Wilmington, NC MSA'),
('NORTH CAROLINA','NC','NORTHAMPTON','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','ONSLOW','37','Greenville - New Bern - Washington, NC DMA','Jacksonville, NC MSA'),
('NORTH CAROLINA','NC','ORANGE','37','Raleigh - Durham, NC - VA DMA','Raleigh - Durham - Chapel Hill, NC MSA'),
('NORTH CAROLINA','NC','PAMLICO','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','PASQUOTANK','37','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','PENDER','37','Wilmington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','PERQUIMANS','37','Norfolk - Portsmouth - Newport News, VA - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','PERSON','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','PITT','37','Greenville - New Bern - Washington, NC DMA','Greenville, NC MSA'),
('NORTH CAROLINA','NC','POLK','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','RANDOLPH','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Greensboro - Winston-Salem - High Point, NC MSA'),
('NORTH CAROLINA','NC','RICHMOND','37','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','ROBESON','37','Florence - Myrtle Beach, SC - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','ROCKINGHAM','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','ROWAN','37','Charlotte, NC - SC DMA','Charlotte - Gastonia - Rock Hill, NC - SC MSA'),
('NORTH CAROLINA','NC','RUTHERFORD','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','SAMPSON','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','SCOTLAND','37','Florence - Myrtle Beach, SC - NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','STANLY','37','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','STOKES','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Greensboro - Winston-Salem - High Point, NC MSA'),
('NORTH CAROLINA','NC','SURRY','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','SWAIN','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','TRANSYLVANIA','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','TYRRELL','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','UNION','37','Charlotte, NC - SC DMA','Charlotte - Gastonia - Rock Hill, NC - SC MSA'),
('NORTH CAROLINA','NC','VANCE','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','WAKE','37','Raleigh - Durham, NC - VA DMA','Raleigh - Durham - Chapel Hill, NC MSA'),
('NORTH CAROLINA','NC','WARREN','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','WASHINGTON','37','Greenville - New Bern - Washington, NC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','WATAUGA','37','Charlotte, NC - SC DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','WAYNE','37','Raleigh - Durham, NC - VA DMA','Goldsboro, NC MSA'),
('NORTH CAROLINA','NC','WILKES','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','WILSON','37','Raleigh - Durham, NC - VA DMA','Not Assigned to Metro Area (NAM)'),
('NORTH CAROLINA','NC','YADKIN','37','Greensboro - H.Point - W.Salem, NC - VA DMA','Greensboro - Winston-Salem - High Point, NC MSA'),
('NORTH CAROLINA','NC','YANCEY','37','Greenville - Spartanburg, SC- Asheville - And., NC - GA  DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','ADAMS','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','BARNES','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','BENSON','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','BILLINGS','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','BOTTINEAU','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','BOWMAN','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','BURKE','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','BURLEIGH','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Bismarck, ND MSA'),
('NORTH DAKOTA','ND','CASS','38','Fargo - Valley City, ND - MN DMA','Fargo - Moorhead, ND - MN MSA'),
('NORTH DAKOTA','ND','CAVALIER','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','DICKEY','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','DIVIDE','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','DUNN','38','Minot - Bismarck - Dickinson, ND - MT - SD DMA','Not Assigned to Metro Area (NAM)'),
('NORTH DAKOTA','ND','EDDY','38','Fargo - Valley City, ND - MN DMA','Not Assigned to Metro Area (NAM)');
